Repository ilios/frontend, pull requests merged in 2018-05, with the labels that each got.

#3758 Skip empty lines in group upload
  app/components/learnergroup-upload-data.js
  tests/acceptance/learnergroup-bulk-assign-test.js
Labels: Ready for Review, in progress

#3755 Rewrite new program year select
  app/components/new-programyear.js
  app/templates/components/new-programyear.hbs
Labels: Ready for Review, in progress

#3768 Flag non-enabled users in leadership lists
  app/styles/components/leadership-manager.scss
  app/templates/components/leadership-list.hbs
  app/templates/components/leadership-manager.hbs
  tests/integration/components/leadership-list-test.js
  tests/integration/components/leadership-manager-test.js
Labels: Ready for Review, in progress

#3769 Update ilios common
  app/components/detail-cohort-manager.js
  package.json
  yarn.lock
Labels: in progress

#3772 Failing test for issue with session list and dependency update
  app/templates/session/index.hbs
  mirage/helpers/get-all.js
  tests/acceptance/course/sessionlist-test.js
  yarn.lock
Labels: Ready for Review, in progress

#3770 Update Ilios Common
  app/templates/components/programyear-list.hbs
  package.json
  tests/acceptance/program/programyear-list-test.js
  yarn.lock
Labels: Ready for Review, in progress

#3774 Prevent terms with associations from being deleted
  app/templates/components/school-vocabulary-term-manager.hbs
Labels: Ready for Review, in progress

#3777 Update common 14.0.0
  app/components/bulk-new-users.js
  app/components/detail-cohort-manager.js
  app/components/user-profile-cohorts.js
  app/components/user-profile-roles.js
  app/mixins/newuser.js
  app/routes/courses.js
  app/routes/instructor-groups.js
  app/routes/learner-groups.js
  app/routes/programs.js
  package.json
  yarn.lock
Labels: Ready for Review

#3778 Show CI Reports menu item to more users
  app/templates/components/ilios-navigation.hbs
Labels: Ready for Review

#3785 Improve controls when a session type can not be edited
  app/components/school-session-type-form.js
  app/templates/components/school-session-type-form.hbs
  app/templates/components/school-session-type-manager.hbs
  app/templates/components/school-session-types-expanded.hbs
  tests/integration/components/school-session-type-form-test.js
Labels: Ready for Review

#3792 Update worker when user logs in
  app/controllers/login.js
  app/routes/application.js
Labels: Ready for Review, in progress

#3795 Ember cli file saver
  app/components/curriculum-inventory-report-header.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/templates/components/curriculum-inventory-report-header.hbs
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#3798 Update Ember CLI to v3.1.4
  .eslintignore
  .eslintrc.js
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#3800 Lookup schools correctly
  app/routes/pending-user-updates.js
Labels: Ready for Review, in progress

#3799 Improve our README
  README.md
Labels: Ready for Review, in progress

#3804 Fix tooltip styles
  app/components/selectable-terms-list-item.js
  app/styles/components.scss
  app/styles/components/selectable-terms-list-item.scss
  app/styles/components/taxonomy-manager.scss
  app/templates/components/selectable-terms-list-item.hbs
Labels: Ready for Review, in progress

#3805 Prevent deleting instructor group which is attached to a course
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/templates/components/instructorgroup-list.hbs
  tests/acceptance/instructorgroups-test.js
Labels: Ready for Review, in progress

#3802 Subscribe to authentication event instead of overriding method
  app/routes/application.js
Labels: Ready for Review

#3811 removed dependency on ember-cli-js-cookie
  package.json
  yarn.lock
Labels: Ready for Review

#3807 Zebra Stripe Tables
  app/components/curriculum-inventory-sequence-block-session-list.js
  app/styles/components/curriculum-inventory-sequence-block-overview.scss
  app/styles/components/curriculum-inventory-sequence-block-session-manager.scss
  app/styles/components/learnergroup-user-manager.scss
  app/styles/components/my-materials.scss
  app/styles/mixins/main-list.scss
Labels: Ready for Review

#3824 de-select course from curriculum inventory report
  app/components/curriculum-inventory-sequence-block-overview.js
  app/templates/components/curriculum-inventory-sequence-block-overview.hbs
  app/templates/components/new-curriculum-inventory-sequence-block.hbs
  tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
Labels: Ready for Review

#3826 list ILMs in sequence block sessions list and manager, but keep them them not selectable.
  app/components/curriculum-inventory-sequence-block-overview.js
  app/components/curriculum-inventory-sequence-block-session-list.js
  app/components/curriculum-inventory-sequence-block-session-manager.js
  app/templates/components/curriculum-inventory-sequence-block-overview.hbs
  app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
  app/templates/components/curriculum-inventory-sequence-block-session-manager.hbs
  tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
  tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
  tests/integration/components/curriculum-inventory-sequence-block-session-manager-test.js
Labels: Ready for Review

#3841 Remove pre-fill component
  app/components/pre-fill.js
  app/styles/components.scss
  app/styles/components/pre-fill.scss
  app/templates/components/pre-fill.hbs
  tests/integration/components/pre-fill-test.js
Labels: Ready for Review, in progress

#3819 Expand all of the sessions in the list
  app/components/light-table/columns/expand-all.js
  app/components/removable-row.js
  app/components/session-table.js
  app/styles/components/session-table.scss
  app/templates/components/learning-material-table.hbs
  app/templates/components/light-table/columns/expand-all.hbs
  app/templates/components/session-offerings-list.hbs
  app/templates/components/session-table.hbs
  tests/acceptance/course/sessionlist-test.js
Labels: in progress, work in progress

#3844 rm linked sessions from seq block on course change.
  app/components/curriculum-inventory-sequence-block-overview.js
Labels: Ready for Review

#3846 fix various bugs in CI management interface.
  app/components/curriculum-inventory-sequence-block-list.js
  app/components/new-curriculum-inventory-sequence-block.js
  app/templates/curriculum-inventory-report/index.hbs
  app/templates/curriculum-inventory-sequence-block.hbs
  tests/integration/components/curriculum-inventory-sequence-block-list-test.js
Labels: Ready for Review

#3840 Exclude sessions from CI report
  app/components/curriculum-inventory-sequence-block-overview.js
  app/components/curriculum-inventory-sequence-block-session-list.js
  app/components/curriculum-inventory-sequence-block-session-manager.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
  app/templates/components/curriculum-inventory-sequence-block-session-manager.hbs
  tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
  tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
  tests/integration/components/curriculum-inventory-sequence-block-session-manager-test.js
Labels: Ready for Review, in progress
