Repository ilios/frontend, pull requests merged in 2018-04, with the labels that each got.

#3658 remove ability to delete objective with descendants
  app/components/course-objective-list-item.js
  app/components/session-objective-list-item.js
  app/mixins/objective-list-item.js
  app/templates/components/course-objective-list-item.hbs
  app/templates/components/session-objective-list-item.hbs
  tests/integration/components/course-objective-list-item-test.js
  tests/integration/components/course-objective-list-test.js
  tests/integration/components/session-objective-list-item-test.js
  tests/integration/components/session-objective-list-test.js
Labels: Ready for Review, in progress

#3660 layout fix for user search results
  app/styles/components/user-search.scss
Labels: Ready for Review

#3667 Added Error to Group Tool Translations refs #3655
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
Labels: in progress

#3663 Filter terms by title
  app/components/taxonomy-manager.js
  app/styles/components/taxonomy-manager.scss
  app/templates/components/taxonomy-manager.hbs
Labels: Ready for Review, in progress

#3673 Print unpublished sessions for privileged users
  app/components/print-course.js
  app/controllers/print-course.js
  app/templates/components/print-course.hbs
  app/templates/print-course.hbs
  tests/acceptance/course/printcourse-test.js
Labels: Ready for Review, in progress

#3665 Visualize the instructors for a course
  app/components/visualizer-course-instructor-session-type.js
  app/components/visualizer-course-instructor-term.js
  app/components/visualizer-course-instructors.js
  app/controllers/course-visualize-instructors.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/router.js
  app/routes/course-visualize-instructor.js
  app/routes/course-visualize-instructors.js
  app/styles/components.scss
  app/styles/components/course-visualizations.scss
  app/styles/components/course-visualize-instructor.scss
  app/styles/components/course-visualize-instructors.scss
  app/styles/components/visualizer-course-instructor-session-type.scss
  app/styles/components/visualizer-course-instructors.scss
  app/templates/components/visualizer-course-instructor-session-type.hbs
  app/templates/components/visualizer-course-instructor-term.hbs
  app/templates/components/visualizer-course-instructors.hbs
  app/templates/course-visualizations.hbs
  app/templates/course-visualize-instructor.hbs
  app/templates/course-visualize-instructors.hbs
  tests/integration/components/visualizer-course-instructor-session-type-test.js
  tests/integration/components/visualizer-course-instructor-term-test.js
  tests/integration/components/visualizer-course-instructors-test.js
  tests/unit/controllers/course-visualize-instructors-test.js
Labels: Ready for Review, in progress

#3671 Use tasks to manage learner groups
  app/components/learnergroup-summary.js
  app/templates/components/learnergroup-summary.hbs
  tests/acceptance/learnergroup-test.js
  tests/integration/components/learnergroup-summary-test.js
  tests/pages/learner-group.js
Labels: Ready for Review, in progress

#3662 Use new permissions system when creating a course
  app/controllers/courses.js
  app/templates/courses.hbs
  config/environment.js
Labels: Ready for Review, in progress

#3681 Greenkeeper/ember cli 3.1.2
  .eslintrc.js
  package.json
  tests/integration/components/user-profile-bio-test.js
  yarn.lock
Labels: in progress

#3683 Update Dependencies
  config/deprecation-workflow.js
  package.json
  tests/acceptance/instructorgroup-test.js
  tests/acceptance/program/programyear/overview-test.js
  tests/acceptance/program/programyear/terms-test.js
  yarn.lock
Labels: in progress

#3680 Enforce our new permissions system in tests
  config/environment.js
  tests/acceptance/courses-test.js
  tests/pages/courses.js
Labels: Ready for Review, in progress

#3687 Send the model as permissionChecker now requires
  app/controllers/courses.js
  package.json
  yarn.lock
Labels: in progress

#3685 rm subgroups from list when deleting learner group.
  app/controllers/learner-groups.js
  tests/acceptance/learnergroups-test.js
Labels: in progress

#3677 Use new permissions system to enforce course editability
  app/components/course-editing.js
  app/components/course-header.js
  app/components/course-leadership-expanded.js
  app/components/course-overview.js
  app/components/course-summary-header.js
  app/components/ilios-course-details.js
  app/components/learningmaterial-manager.js
  app/components/mesh-manager.js
  app/controllers/course.js
  app/routes/course.js
  app/styles/components/mesh-manager.scss
  app/styles/mixins/ilios-form.scss
  app/templates/components/course-editing.hbs
  app/templates/components/course-leadership-expanded.hbs
  app/templates/components/detail-mesh.hbs
  app/templates/components/detail-objectives.hbs
  app/templates/components/ilios-course-details.hbs
  app/templates/components/learning-material-table-actions.hbs
  app/templates/components/learningmaterial-manager.hbs
  app/templates/components/mesh-manager.hbs
  app/templates/components/new-myreport.hbs
  app/templates/components/objective-manage-descriptors.hbs
  app/templates/course.hbs
  tests/acceptance/course/cohorts-test.js
  tests/acceptance/course/leadership-test.js
  tests/acceptance/course/learningmaterials-test.js
  tests/acceptance/course/mesh-test.js
  tests/acceptance/course/objectivecreate-test.js
  tests/acceptance/course/objectivelist-test.js
  tests/acceptance/course/objectivemesh-test.js
  tests/acceptance/course/objectiveparents-multiplecohorts-test.js
  tests/acceptance/course/objectiveparents-test.js
  tests/acceptance/course/overview-test.js
  tests/acceptance/course/publish-test.js
  tests/acceptance/course/terms-test.js
  tests/integration/components/course-leadership-expanded-test.js
  tests/integration/components/course-overview-test.js
  tests/integration/components/course-summary-header-test.js
  tests/integration/components/learning-material-table-actions-test.js
Labels: Ready for Review, in progress

#3698 Restrict creating school to root users
  app/templates/components/school-list.hbs
  tests/integration/components/school-list-test.js
Labels: Ready for Review, in progress

#3700 Enforce new permissions on programs list
  app/components/program-list.js
  app/controllers/programs.js
  app/templates/components/program-list.hbs
  app/templates/programs.hbs
  tests/acceptance/programs-test.js
  tests/integration/components/program-list-test.js
Labels: Ready for Review, in progress

#3695 Enforce new permissions on instructor groups list
  app/components/instructorgroup-list.js
  app/controllers/instructor-groups.js
  app/templates/components/instructorgroup-list.hbs
  app/templates/instructor-groups.hbs
  tests/acceptance/instructorgroups-test.js
Labels: Ready for Review, in progress

#3693 Enforce new permissions in learner groups
  app/components/learnergroup-cohort-user-manager.js
  app/components/learnergroup-header.js
  app/components/learnergroup-list.js
  app/components/learnergroup-subgroup-list.js
  app/components/learnergroup-summary.js
  app/controllers/learner-group.js
  app/controllers/learner-groups.js
  app/routes/learner-group.js
  app/templates/components/learnergroup-cohort-user-manager.hbs
  app/templates/components/learnergroup-header.hbs
  app/templates/components/learnergroup-list.hbs
  app/templates/components/learnergroup-subgroup-list.hbs
  app/templates/components/learnergroup-summary.hbs
  app/templates/learner-group.hbs
  app/templates/learner-groups.hbs
  tests/acceptance/learnergroup-bulk-assign-test.js
  tests/acceptance/learnergroup-test.js
  tests/acceptance/learnergroups-test.js
  tests/integration/components/learnergroup-cohort-user-manager-test.js
  tests/integration/components/learnergroup-header-test.js
  tests/integration/components/learnergroup-subgroup-list-test.js
  tests/integration/components/learnergroup-summary-test.js
Labels: Ready for Review, in progress

#3697 Improve flaky test
  tests/integration/components/loading-bar-test.js
Labels: Ready for Review, in progress

#3694 Enforce Permissions on Session List
  app/components/course-sessions.js
  app/controllers/course/index.js
  app/routes/course/index.js
  app/templates/components/course-sessions.hbs
  app/templates/components/session-table-actions.hbs
  app/templates/course/index.hbs
  tests/acceptance/course/mesh-test.js
  tests/acceptance/course/objectivecreate-test.js
  tests/acceptance/course/objectivemesh-test.js
  tests/acceptance/course/objectiveparents-test.js
  tests/acceptance/course/sessionlist-test.js
  tests/integration/components/session-table-actions-test.js
Labels: Ready for Review, in progress

#3704 Use permissions system for instructor group editability
  app/components/instructorgroup-details.js
  app/components/instructorgroup-header.js
  app/routes/instructor-group.js
  app/styles/components/instructorgroup-details.scss
  app/templates/components/instructorgroup-details.hbs
  app/templates/components/instructorgroup-header.hbs
  app/templates/instructor-group.hbs
  tests/acceptance/instructorgroup-test.js
  tests/integration/components/instructorgroup-header-test.js
Labels: in progress

#3703 Control access to admin dashboard with new permissions
  app/components/manage-users-summary.js
  app/components/pending-updates-summary.js
  app/components/unassigned-students-summary.js
  app/routes/admin-dashboard.js
  app/templates/admin-dashboard.hbs
  app/templates/components/manage-users-summary.hbs
  app/templates/components/pending-updates-summary.hbs
  app/templates/components/unassigned-students-summary.hbs
  tests/acceptance/admin-test.js
  tests/helpers/setup-authentication.js
  tests/integration/components/manage-users-summary-test.js
  tests/integration/components/pending-updates-summary-test.js
  tests/integration/components/unassigned-students-summary-test.js
Labels: Ready for Review, in progress

#3705 Enforce permissions for school management
  app/components/competency-title-editor.js
  app/components/school-competencies-expanded.js
  app/components/school-competencies-manager.js
  app/components/school-manager.js
  app/components/school-session-attributes-expanded.js
  app/components/school-session-attributes.js
  app/components/school-session-type-form.js
  app/components/school-session-type-manager.js
  app/components/school-session-types-expanded.js
  app/components/school-session-types-list.js
  app/components/school-vocabularies-expanded.js
  app/components/school-vocabularies-list.js
  app/components/school-vocabulary-manager.js
  app/components/school-vocabulary-term-manager.js
  app/routes/school.js
  app/templates/components/competency-title-editor.hbs
  app/templates/components/school-competencies-expanded.hbs
  app/templates/components/school-competencies-manager.hbs
  app/templates/components/school-leadership-expanded.hbs
  app/templates/components/school-manager.hbs
  app/templates/components/school-session-attributes-expanded.hbs
  app/templates/components/school-session-attributes.hbs
  app/templates/components/school-session-type-form.hbs
  app/templates/components/school-session-type-manager.hbs
  app/templates/components/school-session-types-expanded.hbs
  app/templates/components/school-session-types-list.hbs
  app/templates/components/school-vocabularies-expanded.hbs
  app/templates/components/school-vocabularies-list.hbs
  app/templates/components/school-vocabulary-manager.hbs
  app/templates/components/school-vocabulary-term-manager.hbs
  app/templates/school.hbs
  tests/integration/components/competency-title-editor-test.js
  tests/integration/components/school-competencies-manager-test.js
  tests/integration/components/school-leadership-expanded-test.js
  tests/integration/components/school-session-type-form-test.js
  tests/integration/components/school-session-type-manager-test.js
  tests/integration/components/school-session-types-expanded-test.js
  tests/integration/components/school-session-types-list-test.js
  tests/integration/components/school-vocabularies-list-test.js
  tests/integration/components/school-vocabulary-term-manager-test.js
Labels: Ready for Review, in progress

#3706 Enforce program editability with permissions checker
  app/components/program-details.js
  app/components/program-header.js
  app/components/program-overview.js
  app/components/programyear-list.js
  app/routes/program.js
  app/routes/program/index.js
  app/templates/components/program-details.hbs
  app/templates/components/program-header.hbs
  app/templates/components/program-overview.hbs
  app/templates/components/programyear-list.hbs
  app/templates/program.hbs
  app/templates/program/index.hbs
  tests/acceptance/program/overview-test.js
  tests/acceptance/program/programyear-list-test.js
  tests/acceptance/program/publish-test.js
  tests/unit/components/programyear-list-test.js
Labels: Ready for Review, in progress

#3707 Enforce CI report creation with new permissions system
  app/controllers/curriculum-inventory-reports.js
  app/routes/curriculum-inventory-reports.js
  app/templates/curriculum-inventory-reports.hbs
Labels: Ready for Review, in progress

#3708 Use permission checker to determine course actions
  app/components/ilios-course-list.js
  app/templates/components/ilios-course-list.hbs
  tests/acceptance/courses-test.js
Labels: Ready for Review, in progress

#3723 Spell Manageable correctly
  app/components/user-profile-bio.js
  app/components/user-profile-cohorts.js
  app/components/user-profile-ics.js
  app/components/user-profile-roles.js
  app/components/user-profile-schools.js
  app/templates/components/user-profile-bio.hbs
  app/templates/components/user-profile-cohorts.hbs
  app/templates/components/user-profile-ics.hbs
  app/templates/components/user-profile-roles.hbs
  app/templates/components/user-profile-schools.hbs
  app/templates/components/user-profile.hbs
  tests/integration/components/user-profile-bio-test.js
  tests/integration/components/user-profile-cohorts-test.js
  tests/integration/components/user-profile-ics-test.js
  tests/integration/components/user-profile-roles-test.js
  tests/integration/components/user-profile-schools-test.js
Labels: Ready for Review, in progress

#3722 Use new permissions when deciding actions on a report
  app/services/reporting.js
Labels: Ready for Review, in progress

#3720 Use editability to determine if an offering can be deleted
  app/components/offering-manager.js
  app/templates/components/offering-manager.hbs
Labels: Ready for Review, in progress

#3726 yanked feature flag and old perms checks.
  app/components/course-overview.js
  app/components/course-sessions.js
  app/components/course-summary-header.js
  app/components/curriculum-inventory-report-overview.js
  app/components/dashboard-mycourses.js
  app/components/ilios-course-list.js
  app/components/offering-manager.js
  app/components/program-list.js
  app/components/programyear-list.js
  app/components/session-copy.js
  app/components/session-overview.js
  app/controllers/courses.js
  app/controllers/curriculum-inventory-reports.js
  app/controllers/instructor-groups.js
  app/controllers/learner-groups.js
  app/controllers/programs.js
  app/routes/admin-dashboard.js
  app/routes/course.js
  app/routes/course/index.js
  app/routes/instructor-group.js
  app/routes/learner-group.js
  app/routes/print-course.js
  app/routes/program-year.js
  app/routes/program-year/index.js
  app/routes/program.js
  app/routes/program/index.js
  app/routes/school.js
  app/routes/session/copy.js
  app/routes/session/index.js
  app/routes/user.js
  app/services/reporting.js
  config/environment.js
Labels: Ready for Review, in progress

#3734 Remove all associations from mirage factories
  mirage/factories/competency.js
  mirage/factories/course-learning-material.js
  mirage/factories/course.js
  mirage/factories/instructor-group.js
  mirage/factories/permission.js
  mirage/factories/program.js
  mirage/factories/school-config.js
  mirage/factories/session.js
  tests/acceptance/course/objectivelist-test.js
  tests/acceptance/course/objectiveparents-test.js
  tests/acceptance/course/session/offerings-test.js
  tests/acceptance/course/session/publicationcheck-test.js
  tests/acceptance/dashboard/calendar-test.js
  tests/acceptance/program/programyear/stewards-test.js
  tests/acceptance/program/publicationcheck-test.js
Labels: in progress

#3732 Add session leadership manager
  app/components/leadership-collapsed.js
  app/components/leadership-list.js
  app/components/leadership-manager.js
  app/components/session-details.js
  app/components/session-leadership-expanded.js
  app/controllers/session/index.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/routes/session/index.js
  app/styles/components.scss
  app/styles/components/session-leadership-expanded.scss
  app/templates/components/leadership-collapsed.hbs
  app/templates/components/leadership-list.hbs
  app/templates/components/leadership-manager.hbs
  app/templates/components/session-details.hbs
  app/templates/components/session-leadership-expanded.hbs
  app/templates/session/index.hbs
  tests/acceptance/course/session/leadership-test.js
  tests/integration/components/leadership-collapsed-test.js
  tests/integration/components/leadership-list-test.js
  tests/integration/components/session-leadership-expanded-test.js
  tests/pages/components/leadership-list.js
  tests/pages/components/leadership-manager.js
  tests/pages/session.js
Labels: Ready for Review, in progress

#3729 replaced calls to removed CP.
  app/mixins/newuser.js
  app/routes/courses.js
  app/routes/instructor-groups.js
  app/routes/learner-groups.js
  app/routes/programs.js
  mirage/config.js
  mirage/factories/permission.js
  tests/acceptance/course/session/offerings-management-test.js
  tests/acceptance/courses-test.js
  tests/acceptance/instructorgroups-test.js
  tests/acceptance/learnergroups-test.js
  tests/acceptance/programs-test.js
  tests/helpers/model-list.js
  tests/integration/components/bulk-new-users-test.js
  tests/integration/components/ilios-users-test.js
  tests/integration/components/new-directory-user-test.js
  tests/integration/components/new-user-test.js
Labels: Ready for Review, in progress

#3738 Remove remaining schools references
  app/components/detail-cohort-manager.js
  app/components/new-myreport.js
  app/components/user-profile-cohorts.js
  app/routes/assign-students.js
  app/templates/components/course-rollover.hbs
  app/templates/components/detail-cohorts.hbs
  app/templates/components/user-profile-cohorts.hbs
  tests/acceptance/assignstudents-test.js
  tests/acceptance/course/session/terms-test.js
  tests/acceptance/dashboard/calendar-test.js
  tests/integration/components/course-rollover-test.js
  tests/integration/components/new-myreport-test.js
  tests/integration/components/user-profile-cohorts-test.js
Labels: in progress

#3751 Enforce Permissions on Curriculum Inventory Reports
  app/components/curriculum-inventory-report-details.js
  app/components/curriculum-inventory-report-header.js
  app/components/curriculum-inventory-report-list.js
  app/components/curriculum-inventory-report-overview.js
  app/components/curriculum-inventory-sequence-block-details.js
  app/components/curriculum-inventory-sequence-block-header.js
  app/components/curriculum-inventory-sequence-block-list.js
  app/components/curriculum-inventory-sequence-block-overview.js
  app/controllers/curriculum-inventory-sequence-block.js
  app/routes/curriculum-inventory-report/index.js
  app/routes/curriculum-inventory-sequence-block.js
  app/templates/components/curriculum-inventory-report-details.hbs
  app/templates/components/curriculum-inventory-report-header.hbs
  app/templates/components/curriculum-inventory-report-list.hbs
  app/templates/components/curriculum-inventory-report-overview.hbs
  app/templates/components/curriculum-inventory-sequence-block-details.hbs
  app/templates/components/curriculum-inventory-sequence-block-header.hbs
  app/templates/components/curriculum-inventory-sequence-block-list.hbs
  app/templates/components/curriculum-inventory-sequence-block-overview.hbs
  app/templates/curriculum-inventory-report/index.hbs
  app/templates/curriculum-inventory-sequence-block.hbs
  tests/integration/components/curriculum-inventory-report-details-test.js
  tests/integration/components/curriculum-inventory-report-header-test.js
  tests/integration/components/curriculum-inventory-report-list-test.js
  tests/integration/components/curriculum-inventory-report-overview-test.js
  tests/integration/components/curriculum-inventory-sequence-block-details-test.js
  tests/integration/components/curriculum-inventory-sequence-block-header-test.js
  tests/integration/components/curriculum-inventory-sequence-block-list-test.js
  tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
Labels: Ready for Review, in progress
