Repository ilios/frontend, pull requests merged in 2018-08, with the labels that each got.

#3951 Update Dependencies
  yarn.lock
Labels: Ready for Review, in progress

#3947 list parents, competencies and MeSH terms with objectives in course print view.
  app/templates/components/print-course.hbs
  tests/acceptance/course/printcourse-test.js
Labels: Ready for Review

#3953 top-align items in program year overview.
  app/styles/components/programyear-overview.scss
Labels: Ready for Review

#3959 Update Dependencies
  yarn.lock
Labels: in progress

#3962 corrected table layout for instructor groups list.
  app/templates/components/instructorgroup-list.hbs
Labels: Ready for Review

#3963 consolidated overridden CP away.
  app/components/user-search.js
Labels: Ready for Review

#3964 Update Dependencies
  yarn.lock
Labels: in progress

#3970 Update dependencies
  yarn.lock
Labels: Ready for Review, in progress

#3972 don't show collapso and table if there are no vocabs.
  app/components/school-vocabularies-expanded.js
  app/templates/components/school-vocabularies-list.hbs
  tests/integration/components/school-vocabularies-expanded-test.js
Labels: Ready for Review

#3973 correct the installation instructions
  README.md
Labels: Ready for Review, in progress

#3976 Remove mocked store from tests
  app/templates/components/new-directory-user.hbs
  tests/integration/components/leadership-search-test.js
  tests/integration/components/learnergroup-subgroup-list-test.js
  tests/integration/components/myreports-list-item-test.js
  tests/integration/components/new-directory-user-test.js
Labels: in progress

#3983 Indicate that all sessions are expanding
  app/components/sessions-grid-header.js
  app/templates/components/course-sessions.hbs
  app/templates/components/sessions-grid-header.hbs
Labels: Ready for Review, in progress

#3984 show the correct duration-totals in list.
  app/templates/components/curriculum-inventory-sequence-block-session-list.hbs
  tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
Labels: Ready for Review, in progress

#3982 When saving an offering highlight it
  app/components/sessions-grid-offering.js
  app/styles/components/sessions-grid-offering-table.scss
Labels: Ready for Review, in progress

#3987 Update common
  app/components/visualizer-program-year-competencies.js
  app/services/reporting.js
  app/templates/components/detail-cohort-list.hbs
  app/templates/components/programyear-header.hbs
  app/templates/components/programyear-list.hbs
  app/templates/program-year-visualizations.hbs
  app/templates/program-year-visualize-competencies.hbs
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#3988 Add title for truncated values
  app/templates/components/sessions-grid-offering.hbs
Labels: Ready for Review, in progress

#3992 Remove deprecated authorize calls
  app/components/file-upload.js
  app/components/programyear-objective-list.js
  config/deprecation-workflow.js
  config/environment.js
Labels: Ready for Review, in progress

#3994 Update some tests
  app/templates/components/bulk-new-users.hbs
  tests/integration/components/bulk-new-users-test.js
  tests/integration/components/manage-users-summary-test.js
Labels: in progress

#3996 Update Dependencies
  yarn.lock
Labels: Ready for Review, in progress

#4000 Handle icons in the froala editor
  app/components/html-editor.js
  config/environment.js
  tests/integration/components/html-editor-test.js
Labels: Ready for Review, in progress

#4005 Give some time for icons to render
  tests/integration/components/html-editor-test.js
Labels: in progress

#4004 Fix the time of these test offerings to 8am
  tests/integration/components/sessions-grid-offering-table-test.js
Labels: Ready for Review, in progress

#4002 Fix collapse course detail icon spacing
  app/styles/components/course-details.scss
  app/templates/components/ilios-course-details.hbs
Labels: Ready for Review, in progress

#3998 Add Instructional Notes to Sessions
  app/components/course-sessions.js
  app/components/editable-field.js
  app/components/session-overview.js
  app/styles/components/session-overview.scss
  app/styles/components/sessions-grid.scss
  app/styles/mixins/sessions-grid.scss
  app/templates/components/session-overview.hbs
  app/templates/components/sessions-grid.hbs
  config/environment.js
  tests/acceptance/course/session/overview-test.js
  tests/acceptance/course/sessionlist-test.js
  tests/pages/components/sessions-grid.js
  tests/pages/session.js
Labels: Ready for Review, in progress

#4006 Make our footer accessible
  app/styles/components/ilios-footer.scss
  tests/acceptance/login-test.js
Labels: Ready for Review, in progress
