Repository ilios/frontend, pull requests merged in 2018-09, with the labels that each got.

#4014 Convert tests to the new test API
  app/components/click-choice-buttons.js
  app/components/pending-updates-summary.js
  app/templates/components/click-choice-buttons.hbs
  app/templates/components/new-user.hbs
  app/templates/components/school-session-type-form.hbs
  app/templates/components/school-vocabularies-list.hbs
  app/templates/components/user-profile-roles.hbs
  mirage/config.js
  mirage/factories/course.js
  mirage/helpers/get-all.js
  mirage/helpers/get-name.js
  tests/integration/components/new-curriculum-inventory-sequence-block-test.js
  tests/integration/components/new-user-test.js
  tests/integration/components/pending-updates-summary-test.js
  tests/integration/components/school-session-type-form-test.js
  tests/integration/components/school-session-type-manager-test.js
  tests/integration/components/school-session-types-expanded-test.js
  tests/integration/components/school-vocabularies-list-test.js
  tests/integration/components/session-copy-test.js
  tests/integration/components/user-profile-roles-test.js
  tests/integration/components/user-search-test.js
Labels: Ready for Review, in progress

#4015 Mark new deprecations
  config/deprecation-workflow.js
Labels: Ready for Review, in progress

#4020 Update Dependencies
  yarn.lock
Labels: Ready for Review, in progress

#4017 Convert report list test to new API
  app/templates/components/curriculum-inventory-report-list.hbs
  tests/integration/components/curriculum-inventory-report-list-test.js
Labels: Ready for Review, in progress

#4022 display error message on login form if user account does not exist
  app/templates/login.hbs
  tests/integration/components/login-form-test.js
Labels: Ready for Review, in progress

#4024 Improve experience when the API version is wrong
  app/components/api-version-check.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/templates/components/api-version-check.hbs
Labels: Ready for Review, in progress

#4032 Update ember-cli-sass
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#4034 Update ember-cli-template-lint to the latest version
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#4038 Update Dependencies
  yarn.lock
Labels: in progress

#4039 disable finalize button on ci report if report has been finalized
  app/styles/components/curriculum-inventory-report-header.scss
  app/templates/components/curriculum-inventory-report-header.hbs
  app/templates/curriculum-inventory-report.hbs
  tests/integration/components/curriculum-inventory-report-details-test.js
  tests/integration/components/curriculum-inventory-report-header-test.js
Labels: Ready for Review, in progress

#4041 bumped ilios-common to latest version.
  package.json
  tests/acceptance/dashboard/calendar-test.js
  yarn.lock
Labels: ready

#4037 thin routes, extending routes-mixins from common.
  app/controllers/course-materials.js
  app/controllers/course-visualize-instructors.js
  app/controllers/course.js
  app/controllers/course/index.js
  app/controllers/course/rollover.js
  app/controllers/print-course.js
  app/controllers/session.js
  app/controllers/session/copy.js
  app/controllers/session/index.js
  app/routes/course-materials.js
  app/routes/course-visualizations.js
  app/routes/course-visualize-instructor.js
  app/routes/course-visualize-instructors.js
  app/routes/course-visualize-objectives.js
  app/routes/course-visualize-session-type.js
  app/routes/course-visualize-session-types.js
  app/routes/course-visualize-term.js
  app/routes/course-visualize-vocabularies.js
  app/routes/course-visualize-vocabulary.js
  app/routes/course.js
  app/routes/course/index.js
  app/routes/course/publishall.js
  app/routes/print-course.js
  app/routes/session.js
  app/routes/session/copy.js
  app/routes/session/index.js
Labels: Ready for Review

#4053 standardized test titles.
  tests/acceptance/admin-test.js
  tests/acceptance/api-version-check-test.js
  tests/acceptance/assignstudents-test.js
  tests/acceptance/course/cohorts-test.js
  tests/acceptance/course/leadership-test.js
  tests/acceptance/course/learningmaterials-test.js
  tests/acceptance/course/mesh-test.js
  tests/acceptance/course/objectivecreate-test.js
  tests/acceptance/course/objectivelist-test.js
  tests/acceptance/course/objectivemesh-test.js
  tests/acceptance/course/objectiveparents-multiplecohorts-test.js
  tests/acceptance/course/objectiveparents-test.js
  tests/acceptance/course/overview-test.js
  tests/acceptance/course/printcourse-test.js
  tests/acceptance/course/publicationcheck-test.js
  tests/acceptance/course/publish-test.js
  tests/acceptance/course/publishall-test.js
  tests/acceptance/course/session/ilm-test.js
  tests/acceptance/course/session/leadership-test.js
  tests/acceptance/course/session/learner-groups-test.js
  tests/acceptance/course/session/learningmaterials-test.js
  tests/acceptance/course/session/mesh-test.js
  tests/acceptance/course/session/objectivecreate-test.js
  tests/acceptance/course/session/objectivelist-test.js
  tests/acceptance/course/session/objectivemesh-test.js
  tests/acceptance/course/session/objectiveparents-test.js
  tests/acceptance/course/session/offerings-management-test.js
  tests/acceptance/course/session/offerings-test.js
  tests/acceptance/course/session/overview-test.js
  tests/acceptance/course/session/publicationcheck-test.js
  tests/acceptance/course/session/publish-test.js
  tests/acceptance/course/session/terms-test.js
  tests/acceptance/course/sessionlist-test.js
  tests/acceptance/course/terms-test.js
  tests/acceptance/curriculum-inventory/leadership-test.js
  tests/acceptance/curriculum-inventory/report-test.js
  tests/acceptance/dashboard/calendar-test.js
  tests/acceptance/dashboard/reports-test.js
  tests/acceptance/four-oh-four-test.js
  tests/acceptance/instructorgroup-test.js
  tests/acceptance/instructorgroups-test.js
  tests/acceptance/learnergroup-test.js
  tests/acceptance/learnergroups-test.js
  tests/acceptance/program/leadership-test.js
  tests/acceptance/program/overview-test.js
  tests/acceptance/program/programyear-list-test.js
  tests/acceptance/program/programyear/competencies-test.js
  tests/acceptance/program/programyear/objectives-test.js
  tests/acceptance/program/programyear/overview-test.js
  tests/acceptance/program/programyear/publicationcheck-test.js
  tests/acceptance/program/programyear/publish-test.js
  tests/acceptance/program/programyear/stewards-test.js
  tests/acceptance/program/programyear/terms-test.js
  tests/acceptance/program/publicationcheck-test.js
  tests/acceptance/program/publish-test.js
  tests/acceptance/programs-test.js
  tests/acceptance/school/session-attributes-test.js
  tests/acceptance/user-test.js
  tests/acceptance/users-test.js
Labels: Ready for Review, ready

#4056 Fix test warnings
  app/components/school-session-attributes.js
  app/templates/components/school-session-attributes.hbs
  tests/integration/components/new-directory-user-test.js
  tests/integration/components/user-profile-cohorts-test.js
Labels: Ready for Review, ready

#4062 Update Dependencies
  yarn.lock
Labels: Ready for Review, in progress

#4066 Try some flakey test mitigations
  .travis.yml
  package.json
  testem.js
  yarn.lock
Labels: Ready for Review, ready

#4070 Remove test logging
  tests/integration/components/course-rollover-test.js
  tests/integration/components/pending-updates-summary-test.js
Labels: Ready for Review, ready

#4067 Remove Percy from our tests
  .travis.yml
  config/environment.js
  package.json
  tests/acceptance/admin-test.js
  tests/acceptance/api-version-check-test.js
  tests/acceptance/assignstudents-test.js
  tests/acceptance/courses-test.js
  tests/acceptance/footer-test.js
  tests/acceptance/four-oh-four-test.js
  tests/acceptance/instructorgroup-test.js
  tests/acceptance/instructorgroups-test.js
  tests/acceptance/learnergroup-bulk-assign-test.js
  tests/acceptance/learnergroup-test.js
  tests/acceptance/learnergroups-test.js
  tests/acceptance/programs-test.js
  tests/acceptance/user-test.js
  tests/acceptance/users-test.js
  tests/integration/components/locale-chooser-test.js
  tests/integration/components/login-form-test.js
  tests/integration/components/user-menu-test.js
  yarn.lock
Labels: Ready for Review, in progress

#4072 Improved tests for api-version-check
  tests/acceptance/api-version-check-test.js
  tests/integration/components/api-version-check-test.js
Labels: ready

#4073 Improve some flaky tests
  tests/integration/components/loading-bar-test.js
  tests/integration/components/sessions-grid-offering-table-test.js
Labels: ready

#4074 Improve async waiters in bulk new users test
  app/components/wait-saving.js
  app/templates/components/bulk-new-users.hbs
  tests/integration/components/bulk-new-users-test.js
Labels: ready

#4075 Improve test waiting for api-version-check
  app/components/api-version-check.js
  tests/integration/components/api-version-check-test.js
Labels: ready

#4061 Greenkeeper/ember data 3.4.2
  app/components/course-objective-list.js
  app/components/course-objective-manager.js
  app/components/detail-instructors.js
  app/components/learningmaterial-manager.js
  app/templates/components/course-objective-list-item.hbs
  app/templates/components/course-objective-list.hbs
  app/templates/components/course-objective-manager.hbs
  app/templates/components/session-details.hbs
  package.json
  tests/integration/components/course-objective-list-test.js
  yarn.lock
Labels: Ready for Review, in progress

#4083 Check for an existing worker before re-loading
  app/routes/application.js
Labels: Ready for Review, ready

#4089 Remove link to slack from our README
  README.md
Labels: Ready for Review, ready
