Repository ilios/frontend, pull requests merged in 2018-11, with the labels that each got.

#4160 "my materials" display fixes
  app/templates/components/my-materials.hbs
  tests/integration/components/my-materials-test.js
Labels: Ready for Review, ready

#4163 stop silencing logger deprecation warnings.
  config/deprecation-workflow.js
Labels: Ready for Review, ready

#4166 adds missing filename attr to test objects.
  tests/integration/components/my-materials-test.js
Labels: Ready for Review

#4164 un-silence jquery event deprecation warning.
  config/deprecation-workflow.js
Labels: Ready for Review

#4170 Remove mirage in preview environment
  config/environment.js
Labels: Ready for Review, ready

#4167 get rid of calls to deprecated sendAction() method.
  app/components/curriculum-inventory-report-header.js
  app/components/curriculum-inventory-report-list.js
  app/components/curriculum-inventory-sequence-block-dates-duration-editor.js
  app/components/curriculum-inventory-sequence-block-list.js
  app/components/curriculum-inventory-sequence-block-min-max-editor.js
  app/components/curriculum-inventory-sequence-block-session-manager.js
  app/components/ilios-course-list.js
  app/components/instructorgroup-list.js
  app/components/myreports-list-item.js
  app/components/new-course.js
  app/components/new-curriculum-inventory-report.js
  app/components/new-curriculum-inventory-sequence-block.js
  app/components/new-directory-user.js
  app/components/new-instructorgroup.js
  app/components/new-learnergroup-multiple.js
  app/components/new-learnergroup-single.js
  app/components/new-learnergroup.js
  app/components/new-myreport.js
  app/components/new-program.js
  app/components/new-user.js
  app/components/offering-editor-learnergroups.js
  app/components/pagedlist-controls.js
  app/components/program-list.js
  app/components/school-session-type-form.js
  app/components/selectable-search-result.js
  app/templates/components/curriculum-inventory-sequence-block-overview.hbs
  app/templates/components/dashboard-myreports.hbs
  app/templates/components/new-learnergroup.hbs
  app/templates/courses.hbs
  app/templates/curriculum-inventory-report/index.hbs
  app/templates/curriculum-inventory-reports.hbs
  app/templates/instructor-groups.hbs
  app/templates/programs.hbs
  config/deprecation-workflow.js
Labels: Ready for Review

#4178 drop instructor cells on smaller screens.
  app/templates/components/my-materials.hbs
Labels: Ready for Review, ready

#4179 properly style "saved" message.
  app/styles/components/curriculum-inventory-sequence-block-list.scss
Labels: Ready for Review

#4177 Add Sentry.io as an OSS hero
  README.md
Labels: Ready for Review, ready

#4154 Add errors reporting with Sentry.io
  app/services/raven.js
  config/environment.js
  ember-cli-build.js
  package.json
  tests/unit/services/raven-test.js
  yarn.lock
Labels: Ready for Review, ready

#4185 Update Dependencies
  yarn.lock
Labels: ready

#4190 render translation string with unescaped html.
  app/templates/components/my-profile.hbs
Labels: Ready for Review

#4188 update components and tests to accomodate for sendAction() removal in common
  app/templates/components/course-director-manager.hbs
  app/templates/components/curriculum-inventory-sequence-block-list.hbs
  app/templates/components/dashboard-myreports.hbs
  app/templates/components/instructorgroup-details.hbs
  app/templates/components/learnergroup-instructor-manager.hbs
  app/templates/components/new-myreport.hbs
  app/templates/components/programyear-list.hbs
  app/templates/components/programyear-overview.hbs
  app/templates/components/school-list.hbs
  app/templates/components/school-session-types-expanded.hbs
  app/templates/components/school-vocabularies-list.hbs
  app/templates/courses.hbs
  app/templates/curriculum-inventory-reports.hbs
  app/templates/instructor-groups.hbs
  app/templates/learner-groups.hbs
  app/templates/programs.hbs
  package.json
  tests/acceptance/program/programyear-list-test.js
  tests/pages/courses.js
  yarn.lock
Labels: Ready for Review
