Repository ilios/frontend, pull requests merged in 2018-03, with the labels that each got.

#3579 Add onOrAfter validation error message
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
Labels: in progress

#3580 Greenkeeper/ember cli mirage 0.4.2
  package.json
  tests/acceptance/course/cohorts-test.js
  tests/helpers/start-mirage.js
  tests/integration/components/collapsed-competencies-test.js
  tests/integration/components/school-session-types-collapsed-test.js
  yarn.lock
Labels: in progress

#3583 Combine tests
  .travis.yml
  tests/integration/components/assign-students-test.js
  tests/integration/components/bulk-new-users-test.js
  tests/integration/components/curriculum-inventory-report-details-test.js
  tests/integration/components/curriculum-inventory-sequence-block-list-test.js
  tests/integration/components/learnergroup-subgroup-list-test.js
  tests/integration/components/my-profile-test.js
  tests/integration/components/new-myreport-test.js
  tests/integration/components/program-list-test.js
  tests/integration/components/school-session-type-form-test.js
Labels: in progress

#3582 Update dependencies
  yarn.lock
Labels: in progress

#3586 Fix code climate
  .codeclimate.yml
  .travis.yml
Labels: in progress

#3585 LInt styles with stylelint
  .sass-lint.yml
  .stylelintrc
  .travis.yml
  app/styles/components.scss
  app/styles/components/breadcrumbs.scss
  app/styles/components/new-curriculum-inventory-sequence-block.scss
  app/styles/components/new-myreport.scss
  app/styles/components/progress-bar.scss
  app/styles/components/publish-all-sessions.scss
  app/styles/components/session-overview.scss
  app/styles/components/toggle-yesno.scss
  app/styles/components/user-profile-bio.scss
  app/styles/components/visualizer-course-objectives.scss
  app/styles/layout/_layout.scss
  app/styles/mixins/ilios-list.scss
  package.json
  yarn.lock
Labels: in progress

#3587 All course objectives to be linked to multiple parents
  app/components/course-objective-manager.js
  app/templates/components/course-objective-manager.hbs
Labels: Ready for Review, in progress

#3590 Fingerprint our logo
  ember-cli-build.js
Labels: in progress

#3592 Tell code climate where our coverage report is
  .travis.yml
Labels: in progress

#3593 Fix the test reporter ID
  .travis.yml
Labels: in progress

#3597 new competencies are created as active by default.
  app/components/school-competencies-expanded.js
Labels: in progress

#3605 Lint before committing
  package.json
  yarn.lock
Labels: in progress

#3594 Fix alignment of dashboard reports
  app/components/myreports-list-item.js
  app/styles/components/dashboard-myreports.scss
  app/templates/components/dashboard-myreports.hbs
  tests/integration/components/dashboard-myreports-test.js
  tests/pages/dashboard.js
Labels: Ready for Review, in progress

#3609 Fix issue with loading spinner
  app/styles/components/learnergroup-bulk-assignment.scss
Labels: Ready for Review, in progress

#3611 Allow users to be uploaded with unmatched names
  app/components/learnergroup-upload-data.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/styles/components/learnergroup-bulk-assignment.scss
  app/templates/components/learnergroup-upload-data.hbs
  tests/acceptance/learnergroup-bulk-assign-test.js
  tests/pages/learner-group.js
Labels: Ready for Review, in progress

#3625 chore(package): update ember-simple-charts to version 0.11.2
  package.json
  yarn.lock
Labels: in progress

#3624 Remove globals that we no longer support
  .eslintrc.js
Labels: Ready for Review, in progress

#3623 Bump our node to version 8
  .nvmrc
  .travis.yml
  package.json
Labels: Ready for Review, in progress

#3612 Update Dependencies and Remove Unnecessary Addon
  config/dependency-lint.js
  ember-cli-build.js
  lib/sw-skip-wait/index.js
  lib/sw-skip-wait/package.json
  lib/sw-skip-wait/service-worker/index.js
  yarn.lock
Labels: Ready for Review, in progress

#3563 Use different browser configuration for dev
  config/targets.js
Labels: Ready for Review

#3628 Build javascript for all browsers with more than 1% market share
  config/targets.js
Labels: Ready for Review, in progress

#3630 Prevent courses with descendants from being deleted
  app/components/ilios-course-list.js
  tests/acceptance/courses-test.js
Labels: Ready for Review, in progress

#3627 Add stylelint explicitly
  package.json
Labels: Ready for Review, in progress

#3631 Add leadership manager to course
  app/components/course-leadership-expanded.js
  app/components/leadership-collapsed.js
  app/components/leadership-list.js
  app/components/leadership-manager.js
  app/components/leadership-search.js
  app/controllers/course.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/styles/components.scss
  app/styles/components/course-leadership-expanded.scss
  app/styles/components/course-overview.scss
  app/templates/components/course-editing.hbs
  app/templates/components/course-leadership-expanded.hbs
  app/templates/components/course-overview.hbs
  app/templates/components/ilios-course-details.hbs
  app/templates/components/leadership-collapsed.hbs
  app/templates/components/leadership-search.hbs
  app/templates/course.hbs
  tests/acceptance/course/leadership-test.js
  tests/acceptance/course/overview-test.js
  tests/integration/components/course-leadership-expanded-test.js
  tests/integration/components/course-overview-test.js
  tests/pages/components/leadership-collapsed.js
  tests/pages/components/leadership-list.js
  tests/pages/components/leadership-manager.js
  tests/pages/course.js
Labels: Ready for Review, in progress

#3640 Allow learning material title to be edited
  app/components/learningmaterial-manager.js
  app/templates/components/learningmaterial-manager.hbs
  tests/acceptance/course/learningmaterials-test.js
  tests/acceptance/course/session/learningmaterials-test.js
  tests/pages/components/learning-materials.js
Labels: Ready for Review, in progress

#3626 Drop babel polyfill
  ember-cli-build.js
Labels: Ready for Review, in progress

#3647 When a user is updated remove their pending updates
  app/components/user-profile-bio.js
  tests/integration/components/user-profile-bio-test.js
Labels: Ready for Review, in progress

#3641 Fix school switcher in in pending updates summary
  app/components/pending-updates-summary.js
  app/templates/components/pending-updates-summary.hbs
Labels: Ready for Review, in progress

#3639 Improve our unsupported browser error experience
  config/environment.js
  lib/ilios-error/index.js
  lib/ilios-error/public/scripts.js
  package.json
  yarn.lock
Labels: Ready for Review, in progress
