Repository ilios/frontend, pull requests merged in 2018-10, with the labels that each got.

#4092 Go back to upstream ember-pikaday
  package.json
  yarn.lock
Labels: Ready for Review, ready

#4095 Update Dependencies
  ember-cli-build.js
  yarn.lock
Labels: Ready for Review, ready

#4101 Use the new publish all controller mixin
  app/controllers/course/publishall.js
  app/routes/course/publishall.js
  app/templates/course/publishall.hbs
  package.json
  tests/acceptance/course/publishall-test.js
  yarn.lock
Labels: Ready for Review, ready

#4105 Greenkeeper/ember cli dependency lint 1.1.1
  package.json
  yarn.lock
Labels: ready

#4110 Use real models instead of mocks in some tests
  tests/integration/components/bulk-new-users-test.js
  tests/integration/components/new-curriculum-inventory-report-test.js
Labels: ready

#4108 Don't lint templates in tests
  package.json
  yarn.lock
Labels: Ready for Review, ready

#4117 styled program and program-year publication check.
  app/styles/components.scss
  app/styles/components/program-publication-check.scss
  app/styles/components/programyear-publication-check.scss
Labels: ready

#4113 Move tests and validator into common
  app/helpers/count-related.js
  app/helpers/not-in.js
  app/validators/html-presence.js
  package.json
  tests/integration/components/click-choice-button-test.js
  tests/integration/components/collapsed-objectives-test.js
  tests/integration/components/course-leadership-expanded-test.js
  tests/integration/components/course-loading-test.js
  tests/integration/components/course-materials-test.js
  tests/integration/components/course-objective-list-item-test.js
  tests/integration/components/course-sessions-test.js
  tests/integration/components/course-summary-header-test.js
  tests/integration/components/detail-cohort-list-test.js
  tests/integration/components/detail-learnergroups-list-test.js
  tests/integration/components/detail-terms-list-item-test.js
  tests/integration/components/detail-terms-list-test.js
  tests/integration/components/expand-collapse-button-test.js
  tests/integration/components/leadership-collapsed-test.js
  tests/integration/components/leadership-list-test.js
  tests/integration/components/learnergroup-tree-test.js
  tests/integration/components/learningmaterial-search-test.js
  tests/integration/components/new-objective-test.js
  tests/integration/components/new-offering-test.js
  tests/integration/components/progress-bar-test.js
  tests/integration/components/publish-all-sessions-test.js
  tests/integration/components/publish-menu-test.js
  tests/integration/components/search-box-test.js
  tests/integration/components/selectable-terms-list-item-test.js
  tests/integration/components/selectable-terms-list-test.js
  tests/integration/components/session-leadership-expanded-test.js
  tests/integration/components/session-objective-list-item-test.js
  tests/integration/components/session-objective-list-test.js
  tests/integration/components/sessions-grid-header-test.js
  tests/integration/components/sessions-grid-loading-test.js
  tests/integration/components/sessions-grid-offering-test.js
  tests/integration/components/sessions-grid-test.js
  tests/integration/components/sortable-heading-test.js
  tests/integration/components/sortable-th-test.js
  tests/integration/components/taxonomy-manager-test.js
  tests/integration/components/toggle-yesno-test.js
  tests/integration/components/visualizer-course-instructor-session-type-test.js
  tests/integration/components/visualizer-course-instructor-term-test.js
  tests/integration/components/visualizer-course-instructors-test.js
  tests/integration/components/visualizer-course-objectives-test.js
  tests/integration/components/visualizer-course-session-type-test.js
  tests/integration/components/visualizer-course-session-types-test.js
  tests/integration/components/visualizer-course-term-test.js
  tests/integration/components/visualizer-course-vocabularies-test.js
  tests/integration/components/visualizer-course-vocabulary-test.js
  tests/unit/components/expand-collapse-button-test.js
  tests/unit/helpers/count-related-test.js
  tests/unit/helpers/has-many-length-test.js
  tests/unit/helpers/is-in-test.js
  tests/unit/helpers/not-in-test.js
  yarn.lock
Labels: Ready for Review, in progress

#4127 Greenkeeper/caniuse db 1.0.30000893
  package.json
  yarn.lock
Labels: ready

#4124 moved error lang strings into common.
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
Labels: Ready for Review, ready

#4134 Fix waiting in bulk new users test
  tests/integration/components/bulk-new-users-test.js
Labels: ready

#4131 Put tasks into debug mode
  config/environment.js
Labels: ready

#4135 Remove duplicate code
  app/components/boolean-check.js
  app/helpers/remove-html-tags.js
  app/templates/components/boolean-check.hbs
Labels: ready

#4136 Remove migrated test
  tests/acceptance/dashboard/calendar-test.js
Labels: ready

#4146 i18n replacement
  app/components/bulk-new-users.js
  app/components/curriculum-inventory-report-list.js
  app/components/curriculum-inventory-sequence-block-overview.js
  app/components/file-upload.js
  app/components/ilios-course-list.js
  app/components/ilios-navigation.js
  app/components/learnergroup-subgroup-list.js
  app/components/learnergroup-upload-data.js
  app/components/locale-chooser.js
  app/components/manage-users-summary.js
  app/components/new-course.js
  app/components/new-curriculum-inventory-sequence-block.js
  app/components/new-directory-user.js
  app/components/new-myreport.js
  app/components/user-menu.js
  app/components/visualizer-program-year-competencies.js
  app/controllers/application.js
  app/controllers/courses.js
  app/controllers/curriculum-inventory-reports.js
  app/controllers/instructor-groups.js
  app/controllers/learner-groups.js
  app/controllers/programs.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/config.js
  app/locales/fr/translations.js
  app/mixins/report-title.js
  app/routes/application.js
  app/services/reporting.js
  app/templates/components/ilios-course-list.hbs
  app/templates/components/learnergroup-user-manager.hbs
  app/templates/components/pending-single-user-update.hbs
  app/templates/pending-user-updates.hbs
  package.json
  tests/helpers/model-list.js
  tests/integration/components/curriculum-inventory-report-overview-test.js
  tests/integration/components/curriculum-inventory-sequence-block-details-test.js
  tests/integration/components/curriculum-inventory-sequence-block-session-list-test.js
  tests/integration/components/learning-materials-sort-manager-test.js
  tests/integration/components/new-programyear-test.js
  tests/integration/components/objective-sort-manager-test.js
  tests/integration/components/offering-editor-learnergroups-test.js
  tests/integration/components/wait-saving-test.js
  tests/unit/components/file-upload-test.js
  tests/unit/translations-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
  yarn.lock
Labels: ready

#4139 move component tests and dependency into common
  package.json
  tests/integration/components/collapsed-competencies-test.js
  tests/integration/components/collapsed-learnergroups-test.js
  tests/integration/components/course-objective-list-test.js
  tests/integration/components/course-overview-test.js
  tests/integration/components/course-rollover-test.js
  tests/integration/components/html-editor-test.js
  tests/integration/components/leadership-manager-test.js
  tests/integration/components/leadership-search-test.js
  tests/integration/components/learning-materials-sort-manager-test.js
  tests/integration/components/objective-sort-manager-test.js
  tests/integration/components/offering-form-test.js
  tests/integration/components/session-copy-test.js
  tests/integration/components/sessions-grid-offering-table-test.js
  tests/integration/components/user-search-test.js
  tests/integration/components/wait-saving-test.js
  tests/unit/components/boolean-check-test.js
  tests/unit/components/error-display-test.js
  tests/unit/components/file-upload-test.js
  tests/unit/components/programyear-list-test.js
  tests/unit/components/recently-updated-display-test.js
  yarn.lock
Labels: Ready for Review

#4153 Update Dependencies
  yarn.lock
Labels: Ready for Review, ready

#4156 Fix ignore on ember-qunit
  package.json
Labels: ready
