Repository ilios/frontend, pull requests merged in 2018-07, with the labels that each got.

#3894 Test the accessibility of our locale chooser
  app/styles/components/locale-chooser.scss
  tests/integration/components/locale-chooser-test.js
Labels: Ready for Review, in progress

#3901 Visual Diffs with percy.io
  config/environment.js
  package.json
  tests/acceptance/admin-test.js
  tests/acceptance/api-version-check-test.js
  tests/acceptance/assignstudents-test.js
  tests/acceptance/courses-test.js
  tests/acceptance/footer-test.js
  tests/acceptance/four-oh-four-test.js
  tests/acceptance/instructorgroup-test.js
  tests/acceptance/instructorgroups-test.js
  tests/acceptance/learnergroup-bulk-assign-test.js
  tests/acceptance/learnergroup-test.js
  tests/acceptance/learnergroups-test.js
  tests/acceptance/programs-test.js
  tests/acceptance/user-test.js
  tests/acceptance/users-test.js
  yarn.lock
Labels: Ready for Review, in progress

#3905 flag inactive terms as such in school-vocab/term manager.
  app/styles/components/school-vocabulary-manager.scss
  app/styles/components/school-vocabulary-term-manager.scss
  app/templates/components/school-vocabulary-manager.hbs
  app/templates/components/school-vocabulary-term-manager.hbs
  tests/integration/components/school-vocabulary-manager-test.js
  tests/integration/components/school-vocabulary-term-manager-test.js
Labels: Ready for Review

#3909 Add specific titles for second and third snapshots
  tests/acceptance/instructorgroups-test.js
  tests/acceptance/learnergroup-bulk-assign-test.js
  tests/acceptance/user-test.js
Labels: Ready for Review, in progress

#3910 Notify users when a new version is available
  app/components/update-notification.js
  app/templates/application.hbs
  ember-cli-build.js
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#3907 Make login form accessible
  app/components/login-form.js
  app/controllers/login.js
  app/styles/components/login-form.scss
  app/styles/mixins/ilios-form.scss
  app/templates/components/login-form.hbs
  app/templates/login.hbs
  tests/integration/components/login-form-test.js
Labels: Ready for Review, in progress

#3911 Improve the accessibility of our loading and error system
  lib/ilios-error/index.js
  lib/ilios-loading/index.js
  lib/ilios-loading/package.json
  package.json
Labels: Ready for Review, in progress

#3914 better alignment of actions column.
  app/templates/components/curriculum-inventory-report-list.hbs
Labels: Ready for Review

#3926 copy session into the selected course.
  app/templates/components/session-copy.hbs
Labels: in progress

#3928 correct display of "root" attribute in user profile admin console
  app/templates/components/user-profile-roles.hbs
  tests/integration/components/user-profile-roles-test.js
Labels: in progress

#3929 display greyed-out trashbin in objectives list for un-deletable items.
  app/templates/components/course-objective-list-item.hbs
  app/templates/components/session-objective-list-item.hbs
  tests/integration/components/course-objective-list-item-test.js
  tests/integration/components/session-objective-list-item-test.js
Labels: in progress

#3931 display total count of courses in list
  app/templates/courses.hbs
  tests/acceptance/courses-test.js
  tests/pages/courses.js
Labels: Ready for Review

#3930 making room for noscript content to show.
  lib/ilios-loading/index.js
Labels: Ready for Review, in progress

#3935 Remove mock store from some integration tests
  app/components/curriculum-inventory-sequence-block-overview.js
  app/templates/components/leadership-search.hbs
  mirage/factories/curriculum-inventory-academic-level.js
  mirage/helpers/get-all.js
  tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
  tests/integration/components/ilios-users-test.js
  tests/integration/components/leadership-manager-test.js
Labels: Ready for Review, in progress

#3936 Update Dependencies
  yarn.lock
Labels: in progress

#3938 show if attendance is required in course print view.
  app/templates/components/print-course.hbs
Labels: Ready for Review, in progress

#3939 root-level users can work with inactive users in learner group manager.
  app/components/learnergroup-cohort-user-manager.js
  app/components/learnergroup-user-manager.js
  app/templates/components/learnergroup-cohort-user-manager.hbs
  app/templates/components/learnergroup-user-manager.hbs
  tests/integration/components/learnergroup-cohort-user-manager-test.js
  tests/integration/components/learnergroup-user-manager-test.js
Labels: Ready for Review, in progress

#3940 don't show tooltip on top-level groups in offerings list.
  app/templates/components/offering-manager.hbs
Labels: Ready for Review

#3945 bumping API to 1.32
  config/api-version.js
Labels: in progress

#3946 indicate ilms and their attributes in course print view as such.
  app/templates/components/print-course.hbs
  tests/acceptance/course/printcourse-test.js
Labels: Ready for Review, in progress

#3950 don't prohibit deletion of objectives if they have descendants.
  app/mixins/objective-list-item.js
  app/templates/components/course-objective-list-item.hbs
  app/templates/components/session-objective-list-item.hbs
  tests/integration/components/course-objective-list-item-test.js
  tests/integration/components/session-objective-list-item-test.js
Labels: Ready for Review
