Repository ilios/frontend, pull requests merged in 2018-02, with the labels that each got.

#3524 Import small group tool from microapp into Ilios
  app/components/learnergroup-bulk-assignment.js
  app/components/learnergroup-bulk-finalize-users.js
  app/components/learnergroup-bulk-group-matcher.js
  app/components/learnergroup-summary.js
  app/components/learnergroup-upload-data.js
  app/controllers/learner-group.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/styles/components/_table.scss
  app/styles/newcomponents.scss
  app/styles/newcomponents/learnergroup-bulk-assignment.scss
  app/templates/components/learnergroup-bulk-assignment.hbs
  app/templates/components/learnergroup-bulk-finalize-users.hbs
  app/templates/components/learnergroup-bulk-group-matcher.hbs
  app/templates/components/learnergroup-list.hbs
  app/templates/components/learnergroup-summary.hbs
  app/templates/components/learnergroup-upload-data.hbs
  app/templates/learner-group.hbs
  mirage/factories/user.js
  tests/acceptance/learnergroup-bulk-assign-test.js
  tests/acceptance/learnergroup-test.js
  tests/integration/components/bulk-new-users-test.js
  tests/integration/components/learnergroup-subgroup-list-test.js
  tests/integration/components/learnergroup-summary-test.js
  tests/pages/learner-group.js
Labels: Ready for Review, in progress

#3542 Translate errors in learner group upload
  app/components/learnergroup-upload-data.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
Labels: Ready for Review

#3543 Defer script loading
  app/index.html
Labels: Ready for Review, in progress

#3547 Activate/Deactivate vocabularies and terms
  app/components/detail-terms-list-item.js
  app/components/detail-terms-list.js
  app/components/school-vocabularies-list.js
  app/components/school-vocabulary-manager.js
  app/components/school-vocabulary-term-manager.js
  app/components/taxonomy-manager.js
  app/styles/newcomponents.scss
  app/styles/newcomponents/detail-terms-list.scss
  app/styles/newcomponents/school-manager.scss
  app/styles/newcomponents/school-vocabulary-manager.scss
  app/styles/newcomponents/school-vocabulary-term-manager.scss
  app/templates/components/detail-terms-list-item.hbs
  app/templates/components/detail-terms-list.hbs
  app/templates/components/school-vocabulary-manager.hbs
  app/templates/components/school-vocabulary-term-manager.hbs
  app/templates/components/selectable-terms-list.hbs
  app/templates/components/taxonomy-manager.hbs
  tests/acceptance/course/session/terms-test.js
  tests/acceptance/course/terms-test.js
  tests/acceptance/program/programyear/terms-test.js
  tests/integration/components/school-vocabulary-term-manager-test.js
  tests/integration/components/selectable-terms-list-item-test.js
  tests/integration/components/selectable-terms-list-test.js
Labels: Ready for Review, in progress

#3551 Lock time at 8am in tests
  tests/acceptance/learnergroup-test.js
  tests/integration/components/learnergroup-calendar-test.js
Labels: Ready for Review, in progress

#3552 Update Dependencies
  config/dependency-lint.js
  yarn.lock
Labels: in progress

#3553 move inactive terms to bottom of list and label them as such.
  app/components/new-myreport.js
Labels: in progress

#3557 Greenkeeper/ember cli sass 7.2.0
  package.json
  yarn.lock
Labels: in progress

#3556 Async cleanup in tests
  tests/integration/components/assign-students-test.js
  tests/integration/components/collapsed-learnergroups-test.js
  tests/integration/components/collapsed-stewards-test.js
  tests/integration/components/curriculum-inventory-report-details-test.js
  tests/integration/components/curriculum-inventory-sequence-block-list-test.js
  tests/integration/components/detail-learnergroups-list-test.js
  tests/integration/components/leadership-search-test.js
  tests/integration/components/my-profile-test.js
  tests/integration/components/new-myreport-test.js
  tests/integration/components/offering-form-test.js
  tests/integration/components/user-profile-learnergroups-test.js
  tests/integration/components/wait-saving-test.js
Labels: Ready for Review, in progress

#3554 Drop ember-normalize
  ember-cli-build.js
  package.json
  yarn.lock
Labels: Ready for Review, in progress

#3555 Code cleanup in collapsed learner groups component
  app/components/collapsed-learnergroups.js
  app/templates/components/collapsed-learnergroups.hbs
Labels: in progress

#3550 Greenkeeper/ember cli flash 1.6.3
  package.json
  yarn.lock
Labels: in progress

#3558 Replace deprecated Array.contains with Array.includes
  app/components/new-myreport.js
Labels: Ready for Review

#3565 Silence some deprecations
  config/deprecation-workflow.js
Labels: in progress

#3569 implemented missing integration tests.
  tests/integration/components/detail-terms-list-item-test.js
  tests/integration/components/detail-terms-list-test.js
  tests/integration/components/taxonomy-manager-test.js
Labels: in progress

#3560 Add UI for rolling over course with cohorts
  app/components/course-rollover.js
  app/locales/en/translations.js
  app/locales/es/translations.js
  app/locales/fr/translations.js
  app/styles/newcomponents/course-rollover.scss
  app/templates/components/course-rollover.hbs
  config/api-version.js
  tests/integration/components/course-rollover-test.js
Labels: Ready for Review, in progress

#3572 rm dependency on ember-promise-helpers.
  package.json
  yarn.lock
Labels: Ready for Review, in progress
