Repository ilios/frontend, pull requests merged in 2019-04, with the labels that each got.

#4469 ilios-common version bump.
  package-lock.json
  package.json
Labels: ready

#4450 course-materials component query param flow update
  app/routes/course-materials.js
  app/templates/course-materials.hbs
Labels: Ready for Review, ready

#4465 added collapsed-objectives-program-years component
  app/components/collapsed-objectives-program-years.js
  app/styles/components.scss
  app/styles/components/collapsed-objectives-program-years.scss
  app/templates/components/collapsed-objectives-program-years.hbs
  app/templates/components/programyear-details.hbs
  tests/integration/components/collapsed-objectives-program-years-test.js
Labels: Ready for Review, ready

#4472 updates lock file with correct frontend version.
  package-lock.json
Labels: Ready for Review, ready

#4470 can see the entire list of students requiring cohort assignment
  app/components/assign-students.js
  app/controllers/assign-students.js
  app/routes/assign-students.js
  app/templates/assign-students.hbs
  app/templates/components/assign-students.hbs
  app/templates/components/unassigned-students-summary.hbs
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: Ready for Review, ready

#4473 added courses column & updated trash icon control flow
  app/components/learnergroup-list.js
  app/templates/components/learnergroup-list.hbs
  app/templates/learner-groups.hbs
  tests/acceptance/learnergroup-test.js
  tests/acceptance/learnergroups-test.js
  tests/integration/components/learnergroup-subgroup-list-test.js
Labels: Ready for Review, ready

#4480 align is deprecated, use class instead.
  app/templates/components/assign-students.hbs
  app/templates/components/learnergroup-list.hbs
Labels: ready

#4476 title attrs on active/inactive indicators.
  app/templates/components/program-list.hbs
  app/templates/components/programyear-list.hbs
Labels: Ready for Review

#4481 Update Ember to v3.9
  config/deprecation-workflow.js
  config/environment.js
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4486 sets selected year dropdown option properly under course creation
  app/components/new-course.js
  app/templates/components/new-course.hbs
Labels: Ready for Review, ready

#4485 fixed hanging spinner for assign-students component
  app/components/assign-students.js
  app/templates/components/assign-students.hbs
Labels: Ready for Review, ready

#4492 added empty list and search results handlers
  app/breakpoints.js
  app/components/curriculum-inventory-report-list.js
  app/components/ilios-course-list.js
  app/components/instructorgroup-list.js
  app/components/program-list.js
  app/templates/components/curriculum-inventory-report-list.hbs
  app/templates/components/ilios-course-list.hbs
  app/templates/components/instructorgroup-list.hbs
  app/templates/components/learnergroup-list.hbs
  app/templates/components/program-list.hbs
  app/templates/courses.hbs
  app/templates/curriculum-inventory-reports.hbs
  app/templates/instructor-groups.hbs
  app/templates/programs.hbs
  package-lock.json
  package.json
  tests/acceptance/courses-test.js
  tests/acceptance/instructorgroups-test.js
  tests/acceptance/programs-test.js
  tests/integration/components/curriculum-inventory-report-list-test.js
  tests/integration/components/program-list-test.js
  tests/pages/courses.js
Labels: Ready for Review, ready

#4493 removes new course notification on route transition
  app/routes/courses.js
  tests/acceptance/courses-test.js
  tests/pages/courses.js
Labels: Ready for Review, ready

#4503 raise an error if a user appears multiple times in the same upload.
  app/components/learnergroup-upload-data.js
  tests/acceptance/learnergroup-bulk-assign-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: Ready for Review

#4507 set autofocus on username input
  app/templates/components/login-form.hbs
Labels: Ready for Review

#4511 added academic year prefix to dropdown
  app/components/new-myreport.js
  app/templates/components/new-myreport.hbs
Labels: Ready for Review

#4500 updated dashboard template
  app/templates/dashboard.hbs
Labels: Ready for Review, ready
