Repository ilios/frontend, pull requests merged in 2019-11, with the labels that each got.

#4929 Update Transitive Dependencies
  package-lock.json
Labels: Ready for Review, dependencies

#4925 Use fetch service instead of commonAjax
  app/components/curriculum-inventory-report-rollover.js
  app/components/curriculum-inventory-verification-preview.js
  app/components/my-profile.js
  app/components/new-directory-user.js
  app/components/user-profile-bio.js
  app/components/user-profile-calendar.js
  app/routes/application.js
  app/routes/login.js
  tests/integration/components/curriculum-inventory-report-rollover-test.js
  tests/integration/components/curriculum-inventory-verification-preview-test.js
  tests/integration/components/my-profile-test.js
  tests/integration/components/new-directory-user-test.js
  tests/integration/components/user-profile-bio-test.js
  tests/integration/components/user-profile-calendar-test.js
Labels: Ready for Review

#4932 Add information to navigation for active routes
  app/templates/components/ilios-navigation.hbs
Labels: Ready for Review

#4937 Update to Ember 3.14
  .travis.yml
  app/app.js
  app/router.js
  package-lock.json
  package.json
Labels: Ready for Review, dependencies

#4949 Let's Go Octane!
  .ember-cli.js
  config/optional-features.json
  package-lock.json
  package.json
Labels: Ready for Review

#4952 Remove runloop complication from scroll listener
  app/components/dashboard-myreports.js
Labels: Ready for Review

#4970 Build tags
  .travis.yml
Labels: Ready for Review

#4971 brings dev dependency into the fold.
  package-lock.json
  package.json
Labels: Ready for Review

#4974 Thanksgiving Dependency Bump
  package-lock.json
  package.json
Labels: dependencies
