Repository ilios/frontend, pull requests merged in 2019-03, with the labels that each got.

#4384 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: ready

#4383 these serializers can now be found in common.
  app/serializers/course.js
  app/serializers/ilm-session.js
  app/serializers/learning-material.js
  app/serializers/offering.js
  app/serializers/session.js
Labels: Ready for Review, ready

#4386 Replace our use of exists-sync
  config/environment.js
Labels: Ready for Review, ready

#4387 Update to the latest code coverage version
  config/coverage.js
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4390 Fix sentry install in travis
  .travis.yml
Labels: Ready for Review, ready

#4396 Changes to the way we save files
  app/components/curriculum-inventory-report-header.js
  app/components/programyear-objective-list.js
  ember-cli-build.js
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4405 Update Ilios Common to v24.1.0
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4388 moved remaining serializers and tests into common.
  app/serializers/authentication.js
  app/serializers/curriculum-inventory-export.js
  app/serializers/curriculum-inventory-report.js
  app/serializers/curriculum-inventory-sequence-block.js
  app/serializers/report.js
  tests/unit/serializers/authentication-test.js
  tests/unit/serializers/course-test.js
  tests/unit/serializers/curriculum-inventory-export-test.js
  tests/unit/serializers/curriculum-inventory-report-test.js
  tests/unit/serializers/curriculum-inventory-sequence-block-test.js
  tests/unit/serializers/ilm-session-test.js
  tests/unit/serializers/learning-material-test.js
  tests/unit/serializers/offering-test.js
  tests/unit/serializers/report-test.js
  tests/unit/serializers/session-test.js
Labels: Ready for Review

#4409 Update common to 25.0.0
  config/api-version.js
  package-lock.json
  package.json
Labels: ready

#4422 Mostly remove service workers
  app/templates/application.hbs
  ember-cli-build.js
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4412 Fix version in error reports
  app/services/raven.js
Labels: Ready for Review, ready

#4423 adds preferred email to user admin form.
  app/components/user-profile-bio.js
  app/templates/components/user-profile-bio.hbs
  tests/integration/components/user-profile-bio-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: Ready for Review, ready

#4438 create new program-years as published
  app/components/programyear-list.js
  app/templates/components/new-programyear.hbs
  tests/acceptance/program/programyear-list-test.js
  tests/integration/components/new-programyear-test.js
Labels: Ready for Review, ready

#4436 create new programs as published.
  app/components/new-program.js
  app/templates/components/new-program.hbs
  tests/integration/components/new-program-test.js
Labels: Ready for Review, ready

#4435 Refactor school leadership
  app/components/school-leadership-expanded.js
  app/templates/components/school-leadership-expanded.hbs
  tests/integration/components/school-leadership-expanded-test.js
Labels: Ready for Review, ready

#4441 Remove unnecessary runloop work in tests
  tests/integration/components/bulk-new-users-test.js
  tests/integration/components/curriculum-inventory-report-details-test.js
  tests/integration/components/curriculum-inventory-report-list-test.js
  tests/integration/components/curriculum-inventory-report-rollover-test.js
  tests/integration/components/curriculum-inventory-sequence-block-overview-test.js
  tests/integration/components/ilios-users-test.js
  tests/integration/components/learnergroup-subgroup-list-test.js
  tests/integration/components/myreports-list-item-test.js
  tests/integration/components/new-curriculum-inventory-report-test.js
  tests/integration/components/new-curriculum-inventory-sequence-block-test.js
  tests/integration/components/new-directory-user-test.js
  tests/integration/components/new-user-test.js
  tests/integration/components/pending-updates-summary-test.js
  tests/integration/components/school-session-type-form-test.js
  tests/integration/components/school-session-type-manager-test.js
  tests/integration/components/school-session-types-expanded-test.js
  tests/integration/components/school-vocabularies-list-test.js
  tests/integration/components/school-vocabulary-manager-test.js
  tests/integration/components/school-vocabulary-term-manager-test.js
  tests/integration/components/user-profile-cohorts-test.js
  tests/integration/components/user-profile-roles-test.js
Labels: Ready for Review, ready

#4444 dropdown selected value display bug
  app/components/new-myreport.js
  app/templates/components/new-myreport.hbs
Labels: Ready for Review, ready

#4456 ilios-common version bump.
  package-lock.json
  package.json
Labels: ready

#4443 gracefully deprecate publishing workflow for programs and program-years
  app/components/program-header.js
  app/components/program-list.js
  app/components/programyear-header.js
  app/components/programyear-list.js
  app/controllers/program/index.js
  app/controllers/programs.js
  app/templates/components/program-header.hbs
  app/templates/components/program-list.hbs
  app/templates/components/programyear-header.hbs
  app/templates/components/programyear-list.hbs
  app/templates/program-year.hbs
  app/templates/program/index.hbs
  app/templates/programs.hbs
  tests/acceptance/program/programyear-list-test.js
  tests/acceptance/program/programyear/publish-test.js
  tests/acceptance/program/publish-test.js
  tests/integration/components/program-header-test.js
  tests/integration/components/program-list-test.js
  tests/integration/components/programyear-header-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: Ready for Review

#4457 Remove dependency lint exception
  config/dependency-lint.js
  package-lock.json
Labels: ready

#4458 deletion-confirmation dialogs for small and large screens.
  app/templates/components/program-list.hbs
  app/templates/components/programyear-list.hbs
Labels: Ready for Review, ready
