Repository ilios/frontend, pull requests merged in 2019-02, with the labels that each got.

#4302 Fix dashboard reports year selector
  app/components/dashboard-myreports.js
  app/templates/components/dashboard-myreports.hbs
  tests/integration/components/dashboard-myreports-test.js
  tests/pages/components/dashboard-myreports.js
  tests/pages/dashboard.js
Labels: Ready for Review, ready

#4304 rm temp files.
  ember-modules-codemod.tmp.62176
  ember-modules-codemod.tmp.62177
Labels: ready

#4300 Update common to 22.1.0
  app/helpers/browser-timezone.js
  config/environment.js
  package.json
  tests/integration/helpers/browser-timezone-test.js
  yarn.lock
Labels: Ready for Review, dependencies, ready

#4299 Add Validation for Vocabulary and Term Titles
  app/components/school-vocabulary-manager.js
  app/components/school-vocabulary-term-manager.js
  app/templates/components/school-vocabulary-manager.hbs
  app/templates/components/school-vocabulary-term-manager.hbs
  tests/integration/components/school-vocabulary-manager-test.js
  tests/integration/components/school-vocabulary-term-manager-test.js
  tests/pages/components/school-vocabulary-manager.js
  tests/pages/components/school-vocabulary-term-manager.js
Labels: Ready for Review, ready

#4310 rm obsolete dependency, we're getting tether from ember-simple-charts…
  package.json
  yarn.lock
Labels: Ready for Review, ready

#4314 bumped ilios-common version.
  package.json
  yarn.lock
Labels: Ready for Review, ready

#4305 transform raw events data before displaying them on user profile calendar
  app/components/user-profile-calendar.js
Labels: Ready for Review

#4321 Remove Dependency Lint Exceptions
  config/dependency-lint.js
Labels: Ready for Review, ready

#4322 Add ignored deprecation
  config/deprecation-workflow.js
Labels: Ready for Review, ready

#4327 Update Ilios Common
  package.json
  tests/acceptance/dashboard/reports-test.js
  tests/pages/dashboard.js
  yarn.lock
Labels: ready

#4331 Enable session linking feature
  config/environment.js
Labels: ready

#4332 Add a bundle analyzer
  package.json
  yarn.lock
Labels: Ready for Review, ready

#4333 Improve our error reporting
  .travis.yml
  app/services/raven.js
Labels: Ready for Review, ready

#4343 Move from yarn to NPM
  package-lock.json
  yarn.lock
Labels: Ready for Review, ready

#4346 Update travis to use NPM
  .travis.yml
Labels: ready

#4344 Remove the error reporter
  app/instance-initializers/error.js
Labels: Ready for Review, ready

#4345 Use our shared eslint config for ember apps
  .eslintrc.js
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4353 Only include the icons we use
  config/environment.js
  config/icons.js
Labels: Ready for Review, ready

#4348 Escape regular expressions
  app/components/learnergroup-cohort-user-manager.js
  app/components/learnergroup-user-manager.js
  app/controllers/assign-students.js
  app/controllers/pending-user-updates.js
Labels: Ready for Review, ready

#4357 whitelist cogs icon.
  config/icons.js
Labels: ready

#4359 replace regexp pattern matching with simple in-string search.
  app/components/learnergroup-cohort-user-manager.js
  app/components/learnergroup-user-manager.js
  app/components/my-materials.js
  app/controllers/assign-students.js
  app/controllers/courses.js
  app/controllers/instructor-groups.js
  app/controllers/learner-groups.js
  app/controllers/pending-user-updates.js
  app/controllers/programs.js
Labels: Ready for Review, ready

#4373 Update Ilios common to v24.0.0
  app/router.js
  package-lock.json
  package.json
Labels: ready

#4370 Update navigation to be accessible
  app/styles/components/ilios-navigation.scss
  app/templates/components/ilios-navigation.hbs
  tests/integration/components/ilios-navigation-test.js
Labels: Ready for Review, ready

#4371 Improve sentry release information
  .travis.yml
Labels: Ready for Review, ready

#4372 Remove last bits of Yarn
  Dockerfile
  README.md
Labels: Ready for Review, ready

#4374 Add progress bar for builds
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4375 Some small Build Time Improvements
  config/environment.js
  ember-cli-build.js
Labels: Ready for Review, ready

#4378 Restore mirage assets
  config/environment.js
Labels: ready

#4379 Add test for learner group member count updates
  app/components/learnergroup-header.js
  app/templates/components/learnergroup-header.hbs
  tests/acceptance/learnergroup-test.js
  tests/pages/learner-group.js
Labels: Ready for Review, ready

#4361 enforce iconographic consistency
  app/styles/components/courses-list.scss
  app/styles/components/curriculum-inventory-reports-list.scss
  app/styles/components/curriculum-inventory-sequence-block-list.scss
  app/styles/components/dashboard-myreports.scss
  app/styles/components/instructorgroups-list.scss
  app/styles/components/learnergroup-subgroup-list.scss
  app/styles/components/learnergroups-list.scss
  app/styles/components/programs-list.scss
  app/styles/components/programyear-list.scss
  app/styles/components/school-competencies-manager.scss
  app/styles/components/school-session-types-list.scss
  app/styles/components/school-vocabularies-list.scss
  app/styles/components/school-vocabulary-term-manager.scss
  app/templates/components/curriculum-inventory-report-list.hbs
  app/templates/components/curriculum-inventory-sequence-block-list.hbs
  app/templates/components/dashboard-myreports.hbs
  app/templates/components/ilios-course-list.hbs
  app/templates/components/instructorgroup-list.hbs
  app/templates/components/learnergroup-list.hbs
  app/templates/components/program-list.hbs
  app/templates/components/programyear-list.hbs
  app/templates/components/school-competencies-manager.hbs
  app/templates/components/school-session-types-list.hbs
  app/templates/components/school-vocabularies-list.hbs
  app/templates/components/school-vocabulary-term-manager.hbs
  tests/integration/components/curriculum-inventory-report-list-test.js
  tests/integration/components/school-competencies-manager-test.js
  tests/integration/components/school-session-types-list-test.js
  tests/integration/components/school-vocabularies-list-test.js
  tests/pages/courses.js
Labels: Ready for Review

#4380 Update to ember-cli 3.8
  .gitignore
  config/deprecation-workflow.js
  package-lock.json
  package.json
Labels: Ready for Review, ready

#4381 Remove deprecated router events
  app/router.js
  app/routes/application.js
  config/deprecation-workflow.js
Labels: Ready for Review, ready
