Repository ilios/frontend, pull requests merged in 2019-10, with the labels that each got.

#4855 updates ember-cli-inject-live-reload dependency.
  package-lock.json
  package.json
Labels: Ready for Review

#4869 Update Transitive Dependencies
  package-lock.json
Labels: Ready for Review, dependencies

#4875 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#4880 fixes school/program selector.
  app/controllers/curriculum-inventory-reports.js
  tests/unit/controllers/curriculum-inventory-reports-test.js
Labels: Ready for Review

#4874 lock file update.
  package-lock.json
Labels: Ready for Review

#4891 Add school name to search results
  app/styles/components/course-search-result.scss
  app/templates/components/course-search-result.hbs
  tests/acceptance/search-test.js
  tests/integration/components/course-search-result-test.js
  tests/integration/components/global-search-test.js
  tests/pages/components/course-search-result.js
  tests/pages/components/global-search.js
Labels: Ready for Review

#4890 Replace missing component
  app/templates/pending-user-updates.hbs
Labels: Ready for Review

#4910 Ember 3.13
  app/components/bulk-new-users.js
  app/components/programyear-objective-list-item.js
  app/templates/components/new-directory-user.hbs
  app/templates/components/programyear-objective-list-item.hbs
  config/dependency-lint.js
  package-lock.json
  package.json
  testem.js
  tests/acceptance/program/programyear/objectives-test.js
  tests/integration/components/new-directory-user-test.js
  tests/integration/components/user-profile-permissions-test.js
Labels: Ready for Review, dependencies

#4899 Handle new login response from common
  app/components/login-form.js
  app/templates/components/login-form.hbs
  config/environment.js
Labels: Ready for Review
