Repository ilios/frontend, pull requests merged in 2020-01, with the labels that each got.

#5034 Update Transitive Dependencies
  package-lock.json
Labels: Ready for Review, dependencies

#5035 Remove duplicate translations
  translations/en-us.yaml
Labels: Ready for Review

#5043 Update Ilios Common
  package-lock.json
  package.json
Labels: dependencies

#5046 rm explicit dependency on ember-lifeline.
  package.json
Labels: Ready for Review

#5047 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#5044 Improve Locale Chooser
  app/components/locale-chooser.hbs
  app/components/locale-chooser.js
  app/styles/mixins/header-menu.scss
Labels: Ready for Review

#5051 Label new report button
  app/components/dashboard-myreports.hbs
Labels: Ready for Review, accessibility

#5050 Label locale chooser toggle
  app/components/locale-chooser.hbs
  app/components/locale-chooser.js
Labels: Ready for Review, accessibility

#5053 Move noscript to the bottom of the header
  config/environment.js
  package-lock.json
  package.json
Labels: Ready for Review, accessibility

#5052 Activate a11y tests for the whole dashboard!
  tests/acceptance/dashboard/accessibility.js
Labels: Ready for Review, accessibility

#5060 Name test correctly
  tests/acceptance/dashboard/accessibility-test.js
Labels: Ready for Review, accessibility

#5068 Update Transitive Dependencies
  package-lock.json
Labels: Ready for Review, dependencies

#5073 Add netlify deploy status badge
  README.md
Labels: Ready for Review

#5083 Activating Actions
  .github/workflows/ci.yml
Labels: Ready for Review

#5082 Test and Deploy with Github Actions
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  .travis.yml
  azure-pipelines.yml
  package.json
Labels: Ready for Review

#5084 Add sentry token for action
  .github/workflows/deploy-production.yml
Labels: Ready for Review

#5091 Update Transitive Dependencies
  package-lock.json
Labels: dependencies
