Repository ilios/frontend, pull requests merged in 2020-02, with the labels that each got.

#5107 updates lock file.
  package-lock.json
Labels: Ready for Review

#5108 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#5115 Fix action version
  .github/workflows/coverage.yml
Labels: Ready for Review

#5122 Update Ilios Common to 35.1.1
  package-lock.json
  package.json
Labels: Ready for Review

#5126 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#5139 Update Ember CLI to v3.16.0
  .editorconfig
  package-lock.json
  package.json
  testem.js
Labels: dependencies

#5140 Fix service worker deployment
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
Labels: bug
