Repository ilios/frontend, pull requests merged in 2024-09, with the labels that each got.

#8105 fix courses and LG subgroup table headers
  packages/frontend/app/styles/components/courses/list.scss
  packages/frontend/app/styles/components/courses/root.scss
  packages/frontend/app/styles/components/learner-group/root.scss
Labels: ready to merge

#8104 rm obsolete custom Resource.
  packages/ilios-common/addon/classes/async-process.js
Labels: ready to merge

#8117 indicate needs for accommodation in learner group list.
  packages/frontend/app/components/learner-group/list-item.hbs
  packages/frontend/tests/integration/components/learner-group/list-item-test.js
  packages/frontend/tests/pages/components/learner-group/list-item.js
Labels: ready to merge

#8103 timed releases start/end now intelligently sync with each other
  packages/ilios-common/addon/components/learningmaterial-manager.js
Labels: ready to merge

#8118 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge, run percy tests

#8120 Update Some Automation Timings
  .github/dependabot.yml
  .github/workflows/nightly.yml
  .github/workflows/update-transitive-dependencies.yaml
Labels: ready to merge

#8126 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge, run percy tests

#8116 Remove unneeded ilios common slices
  packages/ilios-common/addon/classes/events-base.js
  packages/ilios-common/addon/components/course/collapsed-objectives.js
  packages/ilios-common/addon/components/course/objective-list-item.js
  packages/ilios-common/addon/components/course/objective-list.js
  packages/ilios-common/addon/components/course/visualize-instructor-session-type-graph.js
  packages/ilios-common/addon/components/course/visualize-instructor.js
  packages/ilios-common/addon/components/course/visualize-objectives-graph.js
  packages/ilios-common/addon/components/course/visualize-vocabulary-graph.js
  packages/ilios-common/addon/components/dashboard/calendar-filters.js
  packages/ilios-common/addon/components/dashboard/calendar.js
  packages/ilios-common/addon/components/dashboard/courses-calendar-filter.js
  packages/ilios-common/addon/components/dashboard/selected-term-tree.js
  packages/ilios-common/addon/components/detail-cohort-list.js
  packages/ilios-common/addon/components/detail-cohort-manager.js
  packages/ilios-common/addon/components/detail-cohorts.js
  packages/ilios-common/addon/components/detail-instructors.js
  packages/ilios-common/addon/components/detail-learnergroups-list.js
  packages/ilios-common/addon/components/detail-learners-and-learner-groups.js
  packages/ilios-common/addon/components/detail-learning-materials-item.js
  packages/ilios-common/addon/components/detail-learning-materials.js
  packages/ilios-common/addon/components/detail-mesh.js
  packages/ilios-common/addon/components/detail-taxonomies.js
  packages/ilios-common/addon/components/learningmaterial-manager.js
  packages/ilios-common/addon/components/learningmaterial-search.js
  packages/ilios-common/addon/components/offering-calendar.js
  packages/ilios-common/addon/components/offering-form.js
  packages/ilios-common/addon/components/print-course.js
  packages/ilios-common/addon/components/selectable-terms-list.js
  packages/ilios-common/addon/components/session-copy.js
  packages/ilios-common/addon/components/session-offerings-list.js
  packages/ilios-common/addon/components/session-overview.js
  packages/ilios-common/addon/components/session/objective-list-item.js
  packages/ilios-common/addon/components/sessions-grid-offering-table.js
  packages/ilios-common/addon/components/sessions-grid.js
  packages/ilios-common/addon/models/curriculum-inventory-report.js
  packages/ilios-common/addon/models/curriculum-inventory-sequence-block.js
  packages/ilios-common/addon/models/learner-group.js
  packages/ilios-common/addon/models/offering.js
  packages/ilios-common/addon/models/session.js
  packages/ilios-common/addon/routes/course-visualize-instructor.js
  packages/ilios-common/addon/routes/course-visualize-instructors.js
  packages/ilios-common/addon/routes/course-visualize-objectives.js
  packages/ilios-common/addon/routes/course-visualize-session-type.js
  packages/ilios-common/addon/routes/course-visualize-session-types.js
  packages/ilios-common/addon/routes/course-visualize-term.js
  packages/ilios-common/addon/routes/course-visualize-vocabularies.js
  packages/ilios-common/addon/routes/course-visualize-vocabulary.js
Labels: ready to merge

#8121 fix Reports table header styles
  packages/frontend/app/styles/components/reports/root.scss
Labels: ready to merge

#8130 Wait for Loaded Cohorts
  packages/frontend/tests/acceptance/dashboard/calendar-test.js
  packages/ilios-common/addon/components/dashboard/calendar.hbs
Labels: ready to merge

#8131 Only Build Good Sourcemaps in Production
  packages/frontend/ember-cli-build.js
Labels: ready to merge

#8134 Remove test-app Percy Tests
  .github/workflows/nightly.yml
  .github/workflows/ui.yml
  .github/workflows/update-transitive-dependencies.yaml
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: ready to merge

#8135 improve Calendar filters display on mobile
  packages/ilios-common/addon/components/dashboard/calendar-filters.hbs
  packages/ilios-common/app/styles/ilios-common/components/dashboard/calendar.scss
  packages/ilios-common/translations/en-us.yaml
  packages/ilios-common/translations/es.yaml
Labels: ready to merge

#8128 Clean up FaIcon template's class attribute
  packages/ilios-common/addon/components/fa-icon.hbs
  packages/ilios-common/addon/components/fa-icon.js
  packages/test-app/tests/integration/components/fa-icon-test.js
Labels: ready to merge

#8136 fix missing session timed release information
  packages/ilios-common/addon/components/timed-release-schedule.js
  packages/test-app/tests/integration/components/timed-release-schedule-test.js
Labels: ready to merge

#8132 consolidate lang strings for the same message
  packages/frontend/app/components/learner-group/list-item.hbs
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
  packages/ilios-common/addon/components/detail-learnergroups-list-item.hbs
  packages/ilios-common/addon/components/learnergroup-tree.hbs
  packages/ilios-common/addon/components/offering-manager.hbs
  packages/ilios-common/translations/en-us.yaml
  packages/ilios-common/translations/es.yaml
  packages/ilios-common/translations/fr.yaml
  packages/test-app/tests/integration/components/detail-learnergroups-list-item-test.js
  packages/test-app/tests/integration/components/learnergroup-selection-manager-test.js
Labels: ready to merge

#8107 rm obsolete ember-metrics package and the GA integration with it.
  packages/frontend/app/initializers/metrics-imports.js
  packages/frontend/app/router.js
  packages/frontend/app/services/ilios-metrics.js
  packages/frontend/config/environment.js
  packages/frontend/package.json
  packages/frontend/tests/unit/initializers/metrics-imports-test.js
  packages/frontend/tests/unit/services/ilios-metrics-test.js
  pnpm-lock.yaml
Labels: ready to merge

#8129 list out sub-groups that need accommodation in indicator icon text.
  packages/frontend/app/components/learner-group/list-item.hbs
  packages/frontend/app/components/learner-group/list-item.js
  packages/frontend/tests/integration/components/learner-group/list-item-test.js
  packages/frontend/tests/pages/components/learner-group/list-item.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
  packages/ilios-common/addon/models/learner-group.js
Labels: ready to merge

#8137 fix some routes that have horizontal scrolling on small screen
  packages/frontend/app/styles/components/curriculum-inventory/new-report.scss
  packages/frontend/app/styles/components/instructor-groups/new.scss
  packages/frontend/app/styles/components/program/new.scss
  packages/frontend/app/styles/mixins/admin-blocks.scss
Labels: ready to merge

#8139 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge

#8138 Update ember-cli to v5.11.0
  packages/frontend/config/ember-cli-update.json
  packages/frontend/package.json
  packages/frontend/tests/helpers/index.js
  packages/ilios-common/package.json
  packages/ilios-common/tests/dummy/config/ember-cli-update.json
  packages/lti-course-manager/config/ember-cli-update.json
  packages/lti-course-manager/package.json
  packages/lti-dashboard/config/ember-cli-update.json
  packages/lti-dashboard/package.json
  packages/test-app/config/ember-cli-update.json
  packages/test-app/package.json
  packages/test-app/tests/helpers/index.js
  pnpm-lock.yaml
Labels: ready to merge

#8143 Disable Array Prototypes
  packages/frontend/config/environment.js
  packages/lti-course-manager/config/environment.js
  packages/lti-dashboard/config/environment.js
Labels: ready to merge

#8141 dashboard->calendar scrolly fixxy
  packages/ilios-common/.lint-todo
  packages/ilios-common/addon/components/dashboard/courses-calendar-filter.hbs
  packages/ilios-common/addon/components/dashboard/courses-calendar-filter.js
Labels: ready to merge

#8148 Assimilation Complete
  .github/CODEOWNERS
Labels: ready to merge

#8149 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge

#8152 Replace Some Render Modifiers in Courses
  packages/ilios-common/.lint-todo
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/detail-competencies.js
  packages/ilios-common/addon/components/course/overview.hbs
  packages/ilios-common/addon/components/course/overview.js
  packages/ilios-common/addon/components/detail-cohort-list.hbs
  packages/ilios-common/addon/components/detail-cohort-list.js
  packages/ilios-common/addon/components/detail-competencies.hbs
  packages/ilios-common/addon/components/detail-competencies.js
  packages/ilios-common/addon/components/detail-mesh.hbs
  packages/ilios-common/addon/components/detail-mesh.js
  packages/ilios-common/addon/components/detail-terms-list.hbs
  packages/ilios-common/addon/components/detail-terms-list.js
  packages/test-app/tests/integration/components/detail-cohort-list-test.js
  packages/test-app/tests/integration/components/detail-competencies-test.js
Labels: ready to merge

#8145 More Improvements to Calendar Courses Filter
  packages/ilios-common/.lint-todo
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/dashboard/courses-calendar-filter.js
  packages/ilios-common/addon/components/dashboard/courses-calendar-filter.hbs
  packages/ilios-common/addon/components/dashboard/courses-calendar-filter.js
  packages/ilios-common/app/styles/ilios-common/components/dashboard/courses-calendar-filter.scss
  packages/test-app/tests/integration/components/dashboard/courses-calendar-filter-test.js
Labels: ready to merge

#8155 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge

#8147 Change the UI Test Label Process
  .github/workflows/dependabot-automerge.yml
  .github/workflows/required-labels.yml
  .github/workflows/ui.yml
  .github/workflows/update-transitive-dependencies.yaml
Labels: run ui tests

#8154 remove more unneeded .slice() calls
  packages/frontend/app/components/new-directory-user.js
  packages/frontend/app/controllers/pending-user-updates.js
  packages/frontend/app/controllers/user.js
  packages/frontend/app/routes/admin-dashboard.js
  packages/frontend/app/routes/pending-user-updates.js
  packages/frontend/app/services/reporting.js
  packages/frontend/app/utils/clone-learner-group.js
  packages/test-app/tests/integration/components/dashboard/week-test.js
  packages/test-app/tests/integration/components/leadership-manager-test.js
  packages/test-app/tests/integration/components/week-glance-test.js
  packages/test-app/tests/unit/models/curriculum-inventory-sequence-block-test.js
Labels: ready to merge

#8133 header icons now sit more vertically centered
  packages/frontend/app/styles/components/global-search-box.scss
  packages/frontend/app/styles/components/ilios-header.scss
  packages/frontend/app/styles/components/user-guide-link.scss
  packages/frontend/app/styles/layout/_layout.scss
Labels: ready to merge

#8156 Updated our Browser Test Matrix
  packages/frontend/testem.browserstack.js
  packages/lti-course-manager/testem.browserstack.js
  packages/lti-dashboard/testem.browserstack.js
  packages/test-app/testem.browserstack.js
Labels: ready to merge

#8157 add proper mixin to school list actions
  packages/frontend/app/styles/components/school-list.scss
Labels: run ui tests

#8153 Upload Coverage Info to Codeclimate
  .github/workflows/ci.yml
  packages/frontend/config/coverage.js
Labels: ready to merge

#8160 Fix course LM search bug
  packages/ilios-common/addon/components/learningmaterial-search.hbs
  packages/ilios-common/addon/components/learningmaterial-search.js
  packages/test-app/tests/integration/components/learningmaterial-search-test.js
Labels: run ui tests

#8158 Admin->Users->View All spacing fix
  packages/frontend/app/styles/components/manage-users-summary.scss
Labels: ready to merge, run ui tests

#8034 add better text truncation method
  packages/frontend/package.json
  packages/frontend/tests/acceptance/course/objectivelist-test.js
  packages/frontend/tests/acceptance/course/session/objectivelist-test.js
  packages/ilios-common/.lint-todo
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/fade-text.js
  packages/ilios-common/addon/components/editable-field.hbs
  packages/ilios-common/addon/components/fade-text.hbs
  packages/ilios-common/addon/components/fade-text.js
  packages/ilios-common/addon/components/objective-sort-manager.hbs
  packages/ilios-common/app/components/fade-text.js
  packages/ilios-common/app/styles/ilios-common/components.scss
  packages/ilios-common/app/styles/ilios-common/components/course/objective-list.scss
  packages/ilios-common/app/styles/ilios-common/components/editinplace.scss
  packages/ilios-common/app/styles/ilios-common/components/fade-text.scss
  packages/ilios-common/app/styles/ilios-common/components/session/objective-list.scss
  packages/ilios-common/app/styles/ilios-common/mixins/sort-manager.scss
  packages/ilios-common/package.json
  packages/lti-dashboard/package.json
  packages/test-app/tests/integration/components/editable-field-test.js
  packages/test-app/tests/integration/components/fade-text-test.js
  pnpm-lock.yaml
Labels: ready to merge, run ui tests

#8162 Add On-Demand Trigger for Nightly Workflow
  .github/workflows/nightly.yml
Labels: run ui tests

#8163 non-editable course/session long objectives now faded
  packages/ilios-common/addon/components/course/objective-list-item.hbs
  packages/ilios-common/addon/components/session/objective-list-item.hbs
Labels: run ui tests

#8164 fix editable headers with extra elements
  packages/ilios-common/app/styles/ilios-common/components/fade-text.scss
Labels: run ui tests

#8166 removes a couple of calls to Array.slice() where they are not needed.
  packages/frontend/app/components/reports/subject/session.js
  packages/frontend/app/controllers/curriculum-inventory-report/index.js
Labels: run ui tests

#8167 adds faded text effect to long parent objectives in courses/sessions
  packages/frontend/app/styles/components/program-year/objectives.scss
  packages/ilios-common/addon/components/course/objective-list-item-parents.hbs
  packages/ilios-common/addon/components/session/objective-list-item-parents.hbs
  packages/ilios-common/app/styles/ilios-common/components/fade-text.scss
  packages/ilios-common/app/styles/ilios-common/mixins/sort-manager.scss
Labels: run ui tests

#8171 fix timed release syncing bug
  packages/ilios-common/addon/components/learningmaterial-manager.js
Labels: run ui tests
