Repository ilios/frontend, pull requests merged in 2024-02, with the labels that each got.

#7598 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, run percy tests

#7602 Cleanup our lint dependencies and scripts
  .github/workflows/ci.yml
  .github/workflows/percy-test-pr.yml
  .github/workflows/percy.yml
  package.json
  packages/frontend/package.json
  packages/ilios-common/package.json
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: run percy tests

#7633 Pin @sentry/ember version
  packages/frontend/package.json
  pnpm-lock.yaml
Labels: dependencies

#7647 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, run percy tests
