Repository ilios/frontend, pull requests merged in 2024-08, with the labels that each got.

#8032 Add Approval to Auto Merge Workflow
  .github/workflows/auto-merge.yml
Labels: ready to merge

#8049 Add Another 90 Days to the Lint Todos
  packages/frontend/.lint-todo
  packages/ilios-common/.lint-todo
  packages/lti-course-manager/.lint-todo
  packages/lti-dashboard/.lint-todo
  packages/test-app/.lint-todo
Labels: ready to merge

#8053 Split Label and Review Process in Automerge Workflow
  .github/workflows/auto-merge.yml
Labels: ready to merge

#8054 Restore Check on Every Step
  .github/workflows/auto-merge.yml
Labels: ready to merge

#8055 Fix Action Again
  .github/workflows/auto-merge.yml
Labels: ready to merge

#8056 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge

#7998 improve User Guide icon
  packages/frontend/app/components/user-guide-link.hbs
  packages/frontend/app/styles/components/ilios-header.scss
  packages/frontend/app/styles/components/user-guide-link.scss
Labels: ready to merge

#8057 Reduce our Dependabot Runs
  .github/dependabot.yml
Labels: ready to merge

#8059 Silence the Mixed Declarations SASS Deprecation
  packages/frontend/ember-cli-build.js
  packages/lti-course-manager/ember-cli-build.js
  packages/lti-dashboard/ember-cli-build.js
  packages/test-app/ember-cli-build.js
Labels: ready to merge

#8060 More Updates to Automerge
  .github/workflows/auto-merge.yml
  .github/workflows/dependabot-automerge.yml
  .github/workflows/update-transitive-dependencies.yaml
Labels: ready to merge

#8065 Use a Test to Check Strings
  .github/workflows/dependabot-automerge.yml
Labels: ready to merge

#8066 Fix Variables in Workflow
  .github/workflows/dependabot-automerge.yml
Labels: ready to merge

#8067 Fix Issues with Report Downloads
  packages/frontend/app/services/reporting.js
  packages/frontend/tests/unit/services/reporting-test.js
Labels: ready to merge

#8062 Remove several component header render modifiers
  packages/frontend/.lint-todo
  packages/frontend/app/components/curriculum-inventory/report-header.hbs
  packages/frontend/app/components/curriculum-inventory/report-header.js
  packages/frontend/app/components/instructor-group/header.hbs
  packages/frontend/app/components/instructor-group/header.js
  packages/frontend/app/components/learner-group/header.hbs
  packages/frontend/app/components/learner-group/header.js
  packages/frontend/app/components/program/header.hbs
  packages/frontend/app/components/program/header.js
  packages/lti-course-manager/.lint-todo
  packages/lti-dashboard/.lint-todo
  packages/test-app/.lint-todo
Labels: ready to merge

#8070 Fix Percy Token
  .github/workflows/nightly.yml
  .github/workflows/ui.yml
Labels: ready to merge

#8069 Remove Broken Statement
  .github/workflows/dependabot-automerge.yml
Labels: ready to merge

#8075 Fix Test in Automerge
  .github/workflows/dependabot-automerge.yml
Labels: ready to merge

#8076 fixed Ember.js test framework deprecation on ember serve
  packages/frontend/config/dependency-lint.js
Labels: ready to merge

#8080 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge, run percy tests

#7857 Learner Groups now use same loading style as Instructor Groups
  packages/frontend/app/components/learner-groups/loading.hbs
  packages/frontend/app/components/learner-groups/root.hbs
  packages/frontend/app/styles/components.scss
  packages/frontend/app/styles/components/learner-groups/loading.scss
  packages/frontend/tests/acceptance/learnergroups-test.js
  packages/frontend/tests/integration/components/learner-groups/loading-test.js
Labels: ready to merge

#8071 show the learner group ancestry as tooltip and a11y label.
  packages/frontend/app/components/learner-group/user-manager.hbs
  packages/frontend/tests/integration/components/learner-group/user-manager-test.js
  packages/frontend/tests/pages/components/learner-group/user-manager.js
  packages/ilios-common/addon/models/learner-group.js
Labels: ready to merge, run percy tests

#8073 unlock download button only after subject reports data has loaded.
  packages/frontend/app/components/reports/subject-results.hbs
  packages/frontend/app/components/reports/subject.hbs
  packages/frontend/app/components/reports/subject.js
  packages/frontend/app/components/reports/subject/competency.js
  packages/frontend/app/components/reports/subject/course.js
  packages/frontend/app/components/reports/subject/instructor-group.js
  packages/frontend/app/components/reports/subject/instructor.js
  packages/frontend/app/components/reports/subject/learning-material.js
  packages/frontend/app/components/reports/subject/mesh-term.js
  packages/frontend/app/components/reports/subject/program-year.js
  packages/frontend/app/components/reports/subject/program.js
  packages/frontend/app/components/reports/subject/session-type.js
  packages/frontend/app/components/reports/subject/session.js
  packages/frontend/app/components/reports/subject/term.js
  packages/frontend/tests/integration/components/reports/subject-results-test.js
Labels: ready to merge, run percy tests

#8083 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge, run percy tests

#8074 Optimize the Instructors for Course Report
  packages/frontend/app/components/reports/subject/instructor.js
  packages/frontend/app/services/reporting.js
  packages/frontend/tests/integration/components/reports/subject/instructor-test.js
  packages/frontend/tests/unit/services/reporting-test.js
Labels: ready to merge

#8086 downgrade ember-a11y-refocus.
  packages/frontend/package.json
  pnpm-lock.yaml
Labels: ready to merge

#8037 Disabled nextPage button on Admin-Users list if no more results to show
  packages/frontend/app/components/ilios-users.hbs
  packages/frontend/app/components/ilios-users.js
  packages/ilios-common/addon/components/pagedlist-controls.js
Labels: ready to merge

#8081 replaces Resources with Tracked Async Data.
  packages/frontend/app/components/program-year/competencies.js
  packages/frontend/app/components/program-year/objective-list.js
  packages/frontend/app/components/school/visualizer-session-type-vocabularies.js
  packages/frontend/app/components/school/visualizer-session-type-vocabulary.js
  packages/frontend/app/components/user-profile-permissions.js
  packages/ilios-common/addon/components/course/objective-list.hbs
  packages/ilios-common/addon/components/course/objective-list.js
  packages/ilios-common/addon/components/dashboard/calendar-filters.hbs
  packages/ilios-common/addon/components/dashboard/calendar-filters.js
  packages/ilios-common/addon/components/dashboard/materials.js
  packages/ilios-common/addon/components/dashboard/selected-vocabulary.js
  packages/ilios-common/addon/components/detail-cohort-manager.js
  packages/ilios-common/addon/components/detail-learnergroups-list-item.js
  packages/ilios-common/addon/components/detail-learnergroups-list.hbs
  packages/ilios-common/addon/components/detail-learnergroups-list.js
  packages/ilios-common/addon/components/detail-learning-materials-item.js
  packages/ilios-common/addon/components/detail-terms-list-item.js
  packages/ilios-common/addon/components/learnergroup-tree.js
  packages/ilios-common/addon/components/selectable-terms-list.js
  packages/ilios-common/addon/components/session-offerings-time-block-offerings.js
  packages/ilios-common/addon/components/sessions-grid-offering-table-offerings.js
  packages/ilios-common/addon/components/sessions-grid.js
  packages/ilios-common/addon/components/taxonomy-manager.js
Labels: ready to merge

#8088 rm unneccessary calls to Array.slice() from ember-data models.
  packages/ilios-common/addon/models/ilm-session.js
  packages/ilios-common/addon/models/session.js
  packages/ilios-common/addon/models/term.js
  packages/ilios-common/addon/models/user.js
  packages/ilios-common/addon/models/vocabulary.js
Labels: ready to merge

#8092 Drop Support for Safari 15.x
  packages/frontend/config/targets.js
  packages/frontend/testem.browserstack.js
  packages/ilios-common/addon/utils/load-polyfills.js
  packages/lti-course-manager/testem.browserstack.js
  packages/lti-dashboard/testem.browserstack.js
  packages/test-app/config/targets.js
  packages/test-app/testem.browserstack.js
Labels: ready to merge

#8089 fixes broken getter and moves it from model into component where it belongs
  packages/frontend/app/components/program-year/objective-list.hbs
  packages/frontend/app/components/program-year/objective-list.js
  packages/ilios-common/addon/models/program-year.js
  packages/test-app/tests/unit/models/program-year-test.js
Labels: ready to merge

#8085 remove unneeded .slice() calls on data in frontend root components
  packages/frontend/app/components/bulk-new-users.js
  packages/frontend/app/components/global-search.js
  packages/frontend/app/components/new-directory-user.js
  packages/frontend/app/components/new-user.js
  packages/frontend/app/components/pending-updates-summary.js
  packages/frontend/app/components/school-competencies-list-item-pcrs.js
  packages/frontend/app/components/school-competencies-manager.js
  packages/frontend/app/components/school-new-vocabulary-form.js
  packages/frontend/app/components/school-vocabularies-list.js
  packages/frontend/app/components/school-vocabulary-manager.js
  packages/frontend/app/components/school-vocabulary-new-term.js
  packages/frontend/app/components/school-vocabulary-term-manager.js
  packages/frontend/app/components/user-profile-permissions.js
  packages/frontend/app/components/user-profile-roles.js
  packages/frontend/app/components/visualizer-program-year-objectives.js
  packages/frontend/tests/integration/components/new-user-test.js
  packages/frontend/tests/integration/components/school-list-test.js
  packages/frontend/tests/integration/components/school-new-vocabulary-form-test.js
Labels: ready to merge

#8094 Split Frontend and LTI Dashboard Deploy
  .github/workflows/deploy-production.yml
Labels: ready to merge

#8093 Enable Sourcemaps for Embroider
  packages/frontend/ember-cli-build.js
Labels: ready to merge

#8091 Add a Custom Sentry Login Metric
  packages/frontend/app/services/session.js
Labels: ready to merge

#8061 reduce padding on LG members/subgroups when none have been added
  packages/frontend/app/components/learner-group/members.hbs
  packages/frontend/app/components/learner-group/root.hbs
  packages/frontend/app/styles/components/courses/list.scss
  packages/frontend/app/styles/components/programs/list.scss
  packages/frontend/app/styles/mixins/main-list.scss
  packages/ilios-common/app/styles/ilios-common/mixins/detail-container.scss
Labels: ready to merge

#8090 fix incorrect offset on new Admin->Users queries
  packages/frontend/app/components/ilios-users.js
Labels: ready to merge

#8102 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, ready to merge, run percy tests

#8095 removed unneeded slice() calls from frontend components in subdirectories
  packages/frontend/app/components/courses/root.js
  packages/frontend/app/components/curriculum-inventory/new-sequence-block.js
  packages/frontend/app/components/curriculum-inventory/report-rollover.js
  packages/frontend/app/components/curriculum-inventory/reports.js
  packages/frontend/app/components/curriculum-inventory/sequence-block-overview.js
  packages/frontend/app/components/curriculum-inventory/sequence-block-session-manager.js
  packages/frontend/app/components/instructor-group/users.js
  packages/frontend/app/components/instructor-groups/root.js
  packages/frontend/app/components/learner-group/bulk-assignment.js
  packages/frontend/app/components/learner-group/calendar.js
  packages/frontend/app/components/learner-group/instructor-manager.js
  packages/frontend/app/components/learner-group/list-item.js
  packages/frontend/app/components/learner-group/root.js
  packages/frontend/app/components/learner-group/upload-data.js
  packages/frontend/app/components/learner-groups/root.js
  packages/frontend/app/components/program-year/competencies.js
  packages/frontend/app/components/program-year/list.js
  packages/frontend/app/components/program-year/managed-competency-list-item.js
  packages/frontend/app/components/program-year/new.js
  packages/frontend/app/components/program-year/objective-list-item-expanded.js
  packages/frontend/app/components/program-year/objective-list-item.js
  packages/frontend/app/components/program-year/objective-list.js
  packages/frontend/app/components/program-year/objectives.js
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/school/visualizer-session-type-vocabularies.js
  packages/frontend/app/components/school/visualizer-session-type-vocabulary.js
  packages/frontend/tests/integration/components/program-year/list-test.js
  packages/frontend/tests/integration/components/school-list-test.js
Labels: ready to merge
