Repository ilios/frontend, pull requests merged in 2025-02, with the labels that each got.

#8346 Update @warp-drive with @ember-data
  .github/dependabot.yml
Labels: run ui tests

#8345 Add pnpm onlyBuiltDependencies Configuration
  package.json
Labels: run ui tests

#8334 Attempt to make all top/left/right margin/padding consistent (eek)
  packages/frontend/app/components/curriculum-inventory/new-sequence-block.hbs
  packages/frontend/app/components/new-user.hbs
  packages/frontend/app/styles/components/assign-students/manager.scss
  packages/frontend/app/styles/components/bulk-new-users.scss
  packages/frontend/app/styles/components/courses/new.scss
  packages/frontend/app/styles/components/courses/root.scss
  packages/frontend/app/styles/components/curriculum-inventory/new-report.scss
  packages/frontend/app/styles/components/curriculum-inventory/new-sequence-block.scss
  packages/frontend/app/styles/components/curriculum-inventory/report-details.scss
  packages/frontend/app/styles/components/curriculum-inventory/sequence-block-header.scss
  packages/frontend/app/styles/components/curriculum-inventory/sequence-block-overview.scss
  packages/frontend/app/styles/components/instructor-group/courses.scss
  packages/frontend/app/styles/components/instructor-group/header.scss
  packages/frontend/app/styles/components/instructor-group/root.scss
  packages/frontend/app/styles/components/instructor-group/users.scss
  packages/frontend/app/styles/components/instructor-groups/new.scss
  packages/frontend/app/styles/components/instructor-groups/root.scss
  packages/frontend/app/styles/components/learner-group/cohort-user-manager.scss
  packages/frontend/app/styles/components/learner-group/header.scss
  packages/frontend/app/styles/components/learner-group/instructors-list.scss
  packages/frontend/app/styles/components/learner-group/members.scss
  packages/frontend/app/styles/components/learner-group/new.scss
  packages/frontend/app/styles/components/learner-group/root.scss
  packages/frontend/app/styles/components/learner-groups/root.scss
  packages/frontend/app/styles/components/new-user.scss
  packages/frontend/app/styles/components/program-overview.scss
  packages/frontend/app/styles/components/program-year/new.scss
  packages/frontend/app/styles/components/program/header.scss
  packages/frontend/app/styles/components/program/new.scss
  packages/frontend/app/styles/components/program/root.scss
  packages/frontend/app/styles/components/reports/new-subject.scss
  packages/frontend/app/styles/components/reports/subject.scss
  packages/frontend/app/styles/components/school-list.scss
  packages/frontend/app/styles/components/school-manager.scss
  packages/frontend/app/styles/components/school-vocabulary-manager.scss
  packages/ilios-common/addon/components/dashboard/materials.hbs
  packages/ilios-common/addon/components/new-session.hbs
  packages/ilios-common/app/styles/ilios-common/components/body.scss
  packages/ilios-common/app/styles/ilios-common/components/course/rollover.scss
  packages/ilios-common/app/styles/ilios-common/components/dashboard/calendar.scss
  packages/ilios-common/app/styles/ilios-common/components/dashboard/materials.scss
  packages/ilios-common/app/styles/ilios-common/components/dashboard/week.scss
  packages/ilios-common/app/styles/ilios-common/components/detail-instructors.scss
  packages/ilios-common/app/styles/ilios-common/components/detail-learners-and-learner-groups.scss
  packages/ilios-common/app/styles/ilios-common/components/detail-learningmaterials.scss
  packages/ilios-common/app/styles/ilios-common/components/new-learningmaterial.scss
  packages/ilios-common/app/styles/ilios-common/components/new-session.scss
  packages/ilios-common/app/styles/ilios-common/components/offering-form.scss
  packages/ilios-common/app/styles/ilios-common/components/print-course.scss
  packages/ilios-common/app/styles/ilios-common/components/publication-menu.scss
  packages/ilios-common/app/styles/ilios-common/components/session-details.scss
  packages/ilios-common/app/styles/ilios-common/components/session-overview.scss
  packages/ilios-common/app/styles/ilios-common/components/weekly-calendar.scss
  packages/ilios-common/app/styles/ilios-common/mixins/course/overview.scss
  packages/ilios-common/app/styles/ilios-common/mixins/detail-container.scss
  packages/ilios-common/app/styles/ilios-common/mixins/ilios-form.scss
  packages/ilios-common/app/styles/ilios-common/mixins/ilios-overview.scss
  packages/ilios-common/app/styles/ilios-common/mixins/main-list.scss
  packages/ilios-common/app/styles/ilios-common/mixins/objectives.scss
Labels: Needs Team Discussion, run ui tests

#8269 [api bump] rm obsolete attribute from MeSH concept model.
  packages/ilios-common/addon/models/mesh-concept.js
  packages/ilios-common/config/api-version.js
Labels: run ui tests

#8349 Remove NewDirectoryUser render modifier
  packages/frontend/.lint-todo
  packages/frontend/app/components/new-directory-user.hbs
  packages/frontend/app/components/new-directory-user.js
Labels: run ui tests

#8353 Fix Token Generation
  packages/frontend/app/components/my-profile.js
  packages/frontend/tests/integration/components/my-profile-test.js
Labels: run ui tests

#8336 Fully Lock Ember Data
  packages/frontend/package.json
  packages/ilios-common/package.json
  packages/lti-course-manager/package.json
  packages/lti-dashboard/package.json
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: run ui tests

#8355 Undoes the effects of FadeText when printing course summary
  packages/ilios-common/addon/components/course/objective-list-item.js
  packages/ilios-common/addon/components/course/objective-list.hbs
  packages/ilios-common/addon/components/print-course.hbs
  packages/ilios-common/app/styles/ilios-common/components/print-course.scss
Labels: run ui tests

#8363 Remove Reporting AcademicYear render modifier
  packages/frontend/.lint-todo
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/reports/subject/new/academic-year.hbs
  packages/frontend/app/components/reports/subject/new/academic-year.js
  packages/frontend/tests/integration/components/reports/subject/new/academic-year-test.js
Labels: run ui tests

#8369 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, run ui tests

#8372 Change Reporting->[Subject]->Academic Year to work like new Competency
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/reports/subject/new/academic-year.hbs
  packages/frontend/app/components/reports/subject/new/academic-year.js
  packages/frontend/tests/integration/components/reports/subject/new/academic-year-test.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8366 Remove Reporting ProgramYear render modifier
  packages/frontend/.lint-todo
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/reports/subject/new/program-year.hbs
  packages/frontend/app/components/reports/subject/new/program-year.js
  packages/frontend/tests/integration/components/reports/subject/new/program-year-test.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8368 Remove Reporting InstructorGroup render modifier
  packages/frontend/.lint-todo
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/reports/subject/new/instructor-group.hbs
  packages/frontend/app/components/reports/subject/new/instructor-group.js
  packages/frontend/tests/integration/components/reports/subject/new/instructor-group-test.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8376 Remove Reporting Program render modifier
  packages/frontend/.lint-todo
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/reports/subject/new/program.hbs
  packages/frontend/app/components/reports/subject/new/program.js
  packages/frontend/tests/acceptance/reports/subjects-test.js
  packages/frontend/tests/integration/components/reports/subject/new/program-test.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8373 Removes icon for editable report titles
  packages/frontend/app/components/reports/subject-header.hbs
Labels: run ui tests

#8375 Remove Reporting Term render modifier
  packages/frontend/.lint-todo
  packages/frontend/app/components/reports/new-subject.js
  packages/frontend/app/components/reports/subject/new/term.hbs
  packages/frontend/app/components/reports/subject/new/term.js
  packages/frontend/tests/integration/components/reports/subject/new/term-test.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8380 Remove PrintCourse render modifiers
  packages/ilios-common/.lint-todo
  packages/ilios-common/addon/components/print-course.hbs
  packages/ilios-common/addon/components/print-course.js
Labels: run ui tests

#8379 Remove WeeklyCalendarEvent render modifier
  packages/ilios-common/.lint-todo
  packages/ilios-common/addon/components/weekly-calendar-event.hbs
  packages/ilios-common/addon/components/weekly-calendar-event.js
Labels: run ui tests

#8377 Fix Courses by Mesh Term Report
  packages/frontend/app/components/reports/subject/course.js
  packages/frontend/app/components/reports/subject/mesh-term.js
  packages/frontend/tests/acceptance/reports/subjects-test.js
  packages/frontend/tests/integration/components/reports/subject/course-test.js
  packages/frontend/tests/integration/components/reports/subject/mesh-term-test.js
Labels: run ui tests
