Repository ilios/frontend, pull requests merged in 2025-07, with the labels that each got.

#8653 Added space to default message when no Program years
  packages/frontend/app/styles/components/program-year/list.scss
Labels: run ui tests

#8660 Added content for `<meta name="description">`
  packages/frontend/app/components/locale-chooser.gjs
  packages/frontend/app/index.html
  packages/ilios-common/translations/en-us.yaml
  packages/ilios-common/translations/es.yaml
  packages/ilios-common/translations/fr.yaml
  packages/lti-course-manager/app/index.html
  packages/lti-dashboard/app/index.html
  packages/test-app/app/index.html
Labels: run ui tests

#8634 only run Acceptance tests when doing visual regression checks in the CI.
  .github/workflows/nightly.yml
  .github/workflows/ui.yml
Labels: run ui tests

#8646 corrects lang string key.
  packages/frontend/app/components/reports/curriculum/choose-course.gjs
  packages/frontend/tests/integration/components/reports/curriculum/choose-course-test.gjs
  packages/frontend/tests/pages/components/reports/curriculum/choose-course.js
Labels: run ui tests

#8650 Add Program and ProgramYear to LG breadcrumbs
  packages/frontend/app/components/learner-group/header.gjs
  packages/frontend/tests/acceptance/learnergroup-test.js
  packages/frontend/tests/integration/components/learner-group/header-test.gjs
Labels: run ui tests

#8651 Change global search year filter default to current academic year
  packages/frontend/app/controllers/search.js
  packages/frontend/tests/acceptance/search-test.js
Labels: run ui tests

#8666 Correct Style of Link Buttons
  packages/ilios-common/app/styles/ilios-common/mixins/ilios-button.scss
Labels: run ui tests

#8669 Update Transitive Dependencies
  packages/ilios-common/CODE_OF_CONDUCT.md
  pnpm-lock.yaml
Labels: run ui tests

#8664 Fix Dashboard->Event->LM note alignment
  packages/ilios-common/addon/components/week-glance/learning-material-list-item.gjs
  packages/ilios-common/app/styles/ilios-common/components/week-glance/learning-materials.scss
  packages/test-app/tests/integration/components/week-glance-event-test.gjs
Labels: run ui tests

#8602 Subject Report object types that use search inputs now focused when validation fails
  packages/frontend/app/components/reports/new-subject.gjs
  packages/frontend/app/components/reports/subject/new/learning-material.gjs
  packages/frontend/app/components/reports/subject/new/session.gjs
  packages/ilios-common/app/styles/ilios-common/components/mesh-manager.scss
  packages/ilios-common/app/styles/ilios-common/components/search-box.scss
Labels: run ui tests

#8673 Fixed incorrect translation key capitalization method
  packages/frontend/app/components/assign-students/root.gjs
  packages/frontend/app/components/flash-messages.gjs
  packages/frontend/app/components/learner-group/bulk-finalize-users.gjs
  packages/frontend/app/components/learner-group/root.gjs
  packages/frontend/app/components/pending-single-user-update.gjs
  packages/frontend/app/components/program-year/competencies.gjs
  packages/frontend/app/components/school-competencies-list-item.gjs
  packages/frontend/app/components/school-manager.gjs
  packages/frontend/app/controllers/pending-user-updates.js
  packages/ilios-common/addon/components/publish-all-sessions.gjs
Labels: run ui tests

#8678 Eighty Six Code Climate
  .github/workflows/ci.yml
  README.md
Labels: run ui tests

#8674 Label Interactive Elements
  packages/frontend/app/components/courses/root.gjs
  packages/frontend/app/components/curriculum-inventory/reports.gjs
  packages/frontend/app/components/curriculum-inventory/sequence-block-list.gjs
  packages/frontend/app/components/curriculum-inventory/sequence-block-overview.gjs
  packages/frontend/app/components/curriculum-inventory/sequence-block-session-manager.gjs
  packages/frontend/app/components/ilios-users.gjs
  packages/frontend/app/components/instructor-group/users.gjs
  packages/frontend/app/components/learner-group/bulk-group-matcher.gjs
  packages/frontend/app/components/program-year/competencies.gjs
  packages/frontend/app/components/program-year/list-item.gjs
  packages/frontend/app/components/program-year/list.gjs
  packages/frontend/app/components/program-year/objectives.gjs
  packages/frontend/app/components/programs/list-item.gjs
  packages/frontend/app/components/programs/root.gjs
  packages/frontend/app/components/school-competencies-expanded.gjs
  packages/frontend/app/components/school-competencies-manager.gjs
  packages/frontend/app/components/school-institutional-information-manager.gjs
  packages/frontend/app/components/school-session-attributes-expanded.gjs
  packages/frontend/app/components/school-session-types-expanded.gjs
  packages/frontend/app/components/school-session-types-list-item.gjs
  packages/frontend/app/components/school-vocabularies-expanded.gjs
  packages/frontend/app/components/school/emails-editor.gjs
  packages/frontend/app/components/user-profile-cohorts.gjs
  packages/frontend/app/components/user-profile-roles.gjs
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
  packages/ilios-common/addon/components/course/objectives.gjs
  packages/ilios-common/addon/components/course/publicationcheck.gjs
  packages/ilios-common/addon/components/course/sessions.gjs
  packages/ilios-common/addon/components/detail-cohorts.gjs
  packages/ilios-common/addon/components/detail-instructors.gjs
  packages/ilios-common/addon/components/detail-learners-and-learner-groups.gjs
  packages/ilios-common/addon/components/detail-learning-materials-item.gjs
  packages/ilios-common/addon/components/detail-learning-materials.gjs
  packages/ilios-common/addon/components/detail-mesh.gjs
  packages/ilios-common/addon/components/detail-taxonomies.gjs
  packages/ilios-common/addon/components/leadership-expanded.gjs
  packages/ilios-common/addon/components/leadership-manager.gjs
  packages/ilios-common/addon/components/offering-manager.gjs
  packages/ilios-common/addon/components/session-offerings.gjs
  packages/ilios-common/addon/components/session/objectives.gjs
  packages/ilios-common/addon/components/sessions-grid-header.gjs
  packages/ilios-common/addon/components/sessions-grid-row.gjs
  packages/ilios-common/app/styles/ilios-common/components/sessions-grid-header.scss
  packages/ilios-common/app/styles/ilios-common/mixins/sessions-grid.scss
Labels: run ui tests

#8676 Limit Integration a11y Tests
  packages/frontend/tests/helpers/index.js
Labels: run ui tests

#8677 Improve Print Course Accessibility
  packages/ilios-common/addon/components/print-course-session.gjs
  packages/ilios-common/addon/components/print-course.gjs
Labels: run ui tests

#8663 Improve login page initial load time
  packages/frontend/app/components/connection-status.gjs
  packages/frontend/app/templates/application.hbs
  packages/frontend/ember-cli-build.js
  packages/ilios-common/addon/components/api-version-notice.gjs
Labels: run ui tests

#8683 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, run ui tests

#8672 Curriculum Reports copy button url now updates with correct report type
  packages/frontend/app/components/my-profile.gjs
  packages/frontend/app/components/reports/curriculum/header.gjs
  packages/frontend/app/components/user-profile-ics.gjs
  packages/frontend/tests/acceptance/reports/curriculum-test.js
  packages/frontend/tests/integration/components/reports/curriculum/header-test.gjs
  packages/frontend/tests/pages/components/reports/curriculum/header.js
  packages/ilios-common/addon/components/copy-button.gjs
  packages/ilios-common/addon/components/ics-feed.gjs
  packages/ilios-common/addon/components/learningmaterial-manager.gjs
  packages/ilios-common/addon/components/offering-url-display.gjs
  packages/test-app/tests/integration/components/copy-button-test.gjs
Labels: run ui tests

#8680 Replace Term Picker Interaction
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/detail-terms-list.js
  packages/ilios-common/addon/components/detail-terms-list-item.gjs
  packages/ilios-common/app/styles/ilios-common/components/detail-terms-list.scss
Labels: run ui tests

#8679 Assorted Accessibility Fixes
  packages/frontend/app/components/course-search-result.gjs
  packages/frontend/app/components/learner-group/cohort-user-manager.gjs
  packages/frontend/app/components/program/header.gjs
  packages/frontend/app/components/reports/subject-header.gjs
  packages/frontend/app/components/school-competencies-manager.gjs
  packages/frontend/app/styles/components/course-search-result.scss
  packages/frontend/app/styles/components/learner-group/cohort-user-manager.scss
  packages/frontend/app/templates/pending-user-updates.hbs
  packages/ilios-common/addon-mirage-support/factories.js
  packages/ilios-common/addon-mirage-support/factories/curriculum-inventory-sequence-block.js
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/session/postrequisite-editor.js
  packages/ilios-common/addon/components/dashboard/selected-vocabulary.gjs
  packages/ilios-common/addon/components/mesh-manager.gjs
  packages/ilios-common/addon/components/session/postrequisite-editor.gjs
Labels: run ui tests

#8685 Adjust Course Year Header Level
  packages/ilios-common/addon/components/course/header.gjs
  packages/ilios-common/app/styles/ilios-common/mixins/course/header.scss
Labels: run ui tests

#8686 Fix Saving Groups UI
  packages/frontend/app/components/learner-group/root.gjs
Labels: run ui tests

#8684 Swap Buttons for Links
  packages/ilios-common/addon/components/publish-all-sessions.gjs
  packages/ilios-common/addon/components/session-publicationcheck.gjs
Labels: run ui tests

#8644 display sessions associated with a given learner-group.
  packages/frontend/app/components/learner-group/course-associations.gjs
  packages/frontend/app/components/learner-group/root.gjs
  packages/frontend/app/controllers/learner-group.js
  packages/frontend/app/styles/components.scss
  packages/frontend/app/styles/components/learner-group/course-associations.scss
  packages/frontend/app/styles/components/learner-group/root.scss
  packages/frontend/app/templates/learner-group.hbs
  packages/frontend/tests/acceptance/learnergroup-test.js
  packages/frontend/tests/integration/components/learner-group/course-associations-test.gjs
  packages/frontend/tests/integration/components/learner-group/root-test.gjs
  packages/frontend/tests/pages/components/learner-group/course-associations.js
  packages/frontend/tests/pages/components/learner-group/root.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8654 V2 Search API
  packages/frontend/app/components/global-search-box.gjs
  packages/frontend/app/components/global-search.gjs
  packages/frontend/app/components/ilios-header.gjs
  packages/frontend/app/controllers/search.js
  packages/frontend/app/styles/components/global-search.scss
  packages/frontend/app/templates/search.hbs
  packages/frontend/tests/acceptance/search-test.js
  packages/frontend/tests/integration/components/global-search-box-test.gjs
  packages/frontend/tests/integration/components/global-search-test.gjs
  packages/frontend/tests/pages/components/global-search-box.js
  packages/frontend/tests/pages/components/global-search.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
  packages/ilios-common/addon/services/search.js
  packages/ilios-common/config/api-version.js
  packages/test-app/tests/unit/services/search-test.js
Labels: safe to deploy, run ui tests

#8695 adds wrapper element around validation error messages
  packages/ilios-common/addon/components/yup-validation-message.gjs
Labels: run ui tests

#8688 Update PNPM to v10.13.1
  package.json
Labels: dependencies, run ui tests

#8692 Check for valid User Profile Calendar events before accessing
  packages/frontend/app/components/user-profile-calendar.gjs
Labels: run ui tests

#8691 Fully Engage a11y Tests
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: run ui tests

#8697 Upgrade to Node v22
  .github/workflows/ci.yml
  .github/workflows/deploy-pr.yml
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  .github/workflows/nightly.yml
  .github/workflows/tag_version.yaml
  .github/workflows/ui.yml
  .github/workflows/update-transitive-dependencies.yaml
  .nvmrc
  package.json
  packages/frontend/package.json
  packages/ilios-common/package.json
  packages/lti-course-manager/package.json
  packages/lti-dashboard/package.json
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: run ui tests

#8703 Avoid Empty Competency List
  packages/ilios-common/addon/components/detail-competencies.gjs
  packages/ilios-common/addon/components/print-course.gjs
Labels: run ui tests

#8696 Global Search Box Style Adjustments
  packages/frontend/app/components/global-search-box.gjs
  packages/frontend/app/styles/components/global-search-box.scss
  packages/frontend/app/styles/components/global-search.scss
  packages/frontend/app/styles/components/ilios-footer.scss
  packages/frontend/app/styles/components/ilios-header.scss
  packages/frontend/app/styles/components/ilios-logo.scss
  packages/frontend/app/styles/layout/_layout.scss
  packages/frontend/app/templates/application.hbs
  packages/frontend/public/assets/images/sunburst.svg
Labels: run ui tests

#8704 Hide Empty Materials Lists
  packages/ilios-common/addon/components/week-glance/learning-material-list.gjs
Labels: run ui tests

#8605 Add missing icon for unpublished ILMs on WaaG and single events
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/fa-icon.js
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/single-event-learningmaterial-list.js
  packages/ilios-common/addon-test-support/ilios-common/page-objects/components/week-glance/learning-material-list.js
  packages/ilios-common/addon/components/fa-icon.gjs
  packages/ilios-common/addon/components/single-event-learningmaterial-list.gjs
  packages/ilios-common/addon/components/single-event.gjs
  packages/ilios-common/addon/components/week-glance-event.gjs
  packages/ilios-common/addon/components/week-glance/learning-material-list.gjs
  packages/test-app/tests/integration/components/fa-icon-test.gjs
  packages/test-app/tests/integration/components/single-event-learningmaterial-list-test.gjs
  packages/test-app/tests/integration/components/week-glance/learning-material-list-test.gjs
Labels: run ui tests

#8714 Fix Course Print Preview objectives from scrolling
  packages/ilios-common/app/styles/ilios-common/components/print-course.scss
Labels: run ui tests

#8706 check if user is authenticated in session before checking user permissions.
  packages/frontend/app/routes/courses.js
  packages/frontend/app/routes/reports.js
  packages/frontend/app/routes/reports/curriculum.js
  packages/frontend/app/routes/reports/index.js
  packages/frontend/app/routes/reports/subject.js
  packages/frontend/app/routes/reports/subjects.js
  packages/ilios-common/addon/routes/course-materials.js
  packages/ilios-common/addon/routes/course-visualizations.js
  packages/ilios-common/addon/routes/course-visualize-instructor.js
  packages/ilios-common/addon/routes/course-visualize-instructors.js
  packages/ilios-common/addon/routes/course-visualize-objectives.js
  packages/ilios-common/addon/routes/course-visualize-session-type.js
  packages/ilios-common/addon/routes/course-visualize-session-types.js
  packages/ilios-common/addon/routes/course-visualize-term.js
  packages/ilios-common/addon/routes/course-visualize-vocabularies.js
  packages/ilios-common/addon/routes/course-visualize-vocabulary.js
  packages/ilios-common/addon/routes/course.js
  packages/ilios-common/addon/routes/course/index.js
  packages/ilios-common/addon/routes/course/publication-check.js
  packages/ilios-common/addon/routes/course/publishall.js
  packages/ilios-common/addon/routes/course/rollover.js
  packages/ilios-common/addon/routes/print-course.js
  packages/ilios-common/addon/routes/session.js
  packages/ilios-common/addon/routes/session/copy.js
  packages/ilios-common/addon/routes/session/index.js
  packages/ilios-common/addon/routes/session/publication-check.js
  packages/ilios-common/addon/services/current-user.js
  packages/test-app/tests/integration/services/current-user-test.js
Labels: run ui tests

#8707 Removed the extra "this" from that "this this" translation
  packages/ilios-common/translations/en-us.yaml
  packages/test-app/tests/integration/components/course/visualize-instructor-session-type-graph-test.gjs
  packages/test-app/tests/integration/components/course/visualize-instructor-term-graph-test.gjs
Labels: run ui tests

#8718 Update Transitive Dependencies
  pnpm-lock.yaml
Labels: dependencies, run ui tests

#8711 Choose Calendar Color Based on Session Type
  packages/ilios-common/addon-mirage-support/factories/schoolevent.js
  packages/ilios-common/addon/components/daily-calendar-event.gjs
  packages/ilios-common/addon/components/ilios-calendar-event-month.gjs
  packages/ilios-common/addon/components/weekly-calendar-event.gjs
  packages/ilios-common/app/styles/ilios-common/components/daily-calendar-event.scss
  packages/ilios-common/app/styles/ilios-common/components/monthly-calendar.scss
  packages/ilios-common/app/styles/ilios-common/components/weekly-calendar-event.scss
  packages/ilios-common/package.json
  pnpm-lock.yaml
Labels: run ui tests

#8715 aggregate school title, course title, and course year into one value/column.
  packages/frontend/app/components/learner-group/course-associations.gjs
  packages/frontend/tests/integration/components/learner-group/course-associations-test.gjs
  packages/frontend/tests/integration/components/learner-group/root-test.gjs
  packages/frontend/tests/pages/components/learner-group/course-associations.js
Labels: run ui tests

#8717 Course Print Preview Overhaul
  packages/ilios-common/addon/components/course/objective-list-item.gjs
  packages/ilios-common/addon/components/course/objective-list.gjs
  packages/ilios-common/addon/components/detail-terms-list.gjs
  packages/ilios-common/addon/components/print-course-session.gjs
  packages/ilios-common/addon/components/print-course.gjs
  packages/ilios-common/addon/components/session/objective-list-item.gjs
  packages/ilios-common/addon/components/session/objective-list.gjs
  packages/ilios-common/app/styles/ilios-common/components/print-course.scss
  packages/ilios-common/app/styles/ilios-common/mixins/ilios-list.scss
  packages/ilios-common/app/styles/ilios-common/mixins/objectives.scss
Labels: run ui tests

#8723 Fix All Weeks Year Calculation
  packages/frontend/tests/acceptance/weeklyevents-test.js
  packages/ilios-common/addon/components/weekly-events.gjs
Labels: run ui tests

#8699 display courses associated with program years in new component
  packages/frontend/app/components/program-year/course-associations.gjs
  packages/frontend/app/components/program-year/courses.gjs
  packages/frontend/app/components/program-year/details.gjs
  packages/frontend/app/controllers/program-year/index.js
  packages/frontend/app/styles/components.scss
  packages/frontend/app/styles/components/program-year/course-associations.scss
  packages/frontend/app/templates/program-year/index.hbs
  packages/frontend/tests/acceptance/program-year/course-associations-test.js
  packages/frontend/tests/integration/components/program-year/course-associations-test.gjs
  packages/frontend/tests/integration/components/program-year/courses-test.gjs
  packages/frontend/tests/pages/components/program-year/course-associations.js
  packages/frontend/tests/pages/components/program-year/courses.js
  packages/frontend/tests/pages/components/program-year/details.js
Labels: run ui tests

#8721 Use replaceState instead of pushState for querystring updates
  packages/frontend/app/routes/assign-students.js
  packages/frontend/app/routes/instructor-group.js
  packages/frontend/app/routes/learner-group.js
  packages/frontend/app/routes/pending-user-updates.js
  packages/frontend/app/routes/program-year/index.js
  packages/frontend/app/routes/program.js
  packages/frontend/app/routes/reports/subjects.js
  packages/ilios-common/addon/routes/course.js
Labels: run ui tests

#8720 Show empty row with message when no data in Curricular Inventory Report tables
  packages/frontend/app/components/curriculum-inventory/verification-preview-table1.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table2.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table3a.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table3b.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table4.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table5.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table6.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table7.gjs
  packages/frontend/app/components/curriculum-inventory/verification-preview-table8.gjs
  packages/frontend/app/styles/components/curriculum-inventory/verification-preview-table2.scss
  packages/frontend/app/styles/components/curriculum-inventory/verification-preview.scss
Labels: run ui tests

#8727 removes misapplied aria labels from button.
  packages/frontend/app/components/instructor-group/course-associations.gjs
  packages/frontend/app/components/learner-group/course-associations.gjs
  packages/frontend/app/components/program-year/course-associations.gjs
  packages/frontend/tests/integration/components/instructor-group/course-associations-test.gjs
  packages/frontend/tests/integration/components/learner-group/course-associations-test.gjs
  packages/frontend/tests/integration/components/program-year/course-associations-test.gjs
  packages/frontend/tests/pages/components/instructor-group/course-associations.js
  packages/frontend/tests/pages/components/learner-group/course-associations.js
  packages/frontend/tests/pages/components/program-year/course-associations.js
  packages/frontend/translations/en-us.yaml
  packages/frontend/translations/es.yaml
  packages/frontend/translations/fr.yaml
Labels: run ui tests

#8729 rm unnecessary top border.
  packages/frontend/app/styles/components/instructor-group/course-associations.scss
  packages/frontend/app/styles/components/program-year/course-associations.scss
Labels: run ui tests
